### ISSUE TITLE
Supporting MathJax extensions

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#1036]
This is coming from #1021, which got hijacked.

We load the `extpfeil` package (LaTeX) and extension (MathJax) automatically.  The package causes a few headaches (seach through `mathbook-latex.xsl`).

We have an existing mechanism for loading packages/extensions, where we place some responsibility on the author to patrol conflicts.  It needs to be redesigned slightly to accomodate cases where extension authors decide to use a different name than the package.

I think I'd prefer to have all these scenarios (including `extpfeil`) be author-supported, not PreTeXt-supported.  Contradicting myself at #389.

Comments?

**Comment by StevenClontz** [comment]
My Unix philosophy is showing: it seems to me that PreTeXt should focus on doing what's most elegant (=> easiest for you to maintain and explain to users), while leaving things compatible for authors who want to wander off the beaten path at their own peril.

To me, this seems like having a subset of the intersection of LaTeX and MathJax supported by PreTeXt directly, and a place in the header for authors to configure LaTeX/MathJax to handle packages/extensions not in that subset.

**Comment by rbeezer** [comment]
I like that philosophy!  ;-)

**Comment by rbeezer** [comment]
Done, and now locating an issue to that effect.  ;-)

Heart of the matter at 16ab3b7aab686e48de3fcfe951acdf5541a9d749 with commits before and after.
