### ISSUE TITLE
Safari GeoGebra bug

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#1063]
While using Safari, if I go here:
https://pretextbook.org/examples/showcase/html/mathematics.html

and turn on the at-the-ready calculator, then scroll down, the calculator disappears.

Also, clicking the Calc button leads to some of the nav bar buttons shifting up a little out of place.

**Comment by kcrisman** [comment]
I should point out that it seems that it only disappears _exactly_ when one scrolls to the bottom of the sidebar TOC (as measured by the bottom of the MathJax logo appearing).  Presumably one could check this by making a fake page with a really long TOC on the side.

**Comment by Alex-Jordan** [comment]
I confirm what KDC reports. But no scrolling is needed at all to see the issue with the buttons shifting up.

**Comment by rbeezer** [comment]
@Alex-Jordan can you try this again, and close if it is resolved?  There have been big changes since this was posted.

**Comment by Alex-Jordan** [comment]
I don't see this anymore. I'm on an old Mac with an old Safari, but I'm still pretty sure that the overhaul changed so much this is not a thing anymore.

**Comment by rbeezer** [comment]
>  overhaul changed so much

Indeed.  Thanks for checking!
