### ISSUE TITLE
Add support in interactive for jsxgraph/JessieCode

### ISSUE THREAD

**Issue by sean-fitzpatrick** [PreTeXtBook/pretext#1093]
JessieCode provides a GeoGeobra-like construction protocol for interactive graphics.
Output does not require an iframe, or so I'm told.
[JessieCode](https://github.com/jsxgraph/JessieCode)

**Comment by rbeezer** [comment]
We've always had `JSXGraph` in one form or another.  JessieCode was added in 889a2a53bf901280453ace6a4ba9f7567439a7b7 as part of #1489.
