### ISSUE TITLE
better missing argument messages for mbx

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#1112]
According to `mbx -h` most of the arguments are optional.  But I don't think they are really, because then I get things like

```
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I think there should be something that says "did you include all arguments" and it should be very clear which arguments are needed.  A bit of experimentation suggests at least `-c`, `-f`, and `-d`, but I haven't read the actual script and may have missed something.

**Comment by davidfarmer** [comment]
CLI takes care of this.
