### ISSUE TITLE
clarify syntax for source file in mbx script

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#1115]
This low-priority enhancement request is to clarify exactly when full paths are necessary for mbx.

----------

The file currently at [the author guide](https://pretextbook.org/doc/author-guide/html/mbx-strategy.html) says
> Certain arguments that are filenames require a full (not relative) path to locate the right objects. In the example above, you can see the source file requires this (where the shell in use here will expand the ~ to the user's home directory). 
However, perhaps surprisingly, when I use 
```
$ ../../mathbook/script/mbx -vv -c sageplot -f svg -d ../images ../src/NTIC.xml 
```
everything seems to work fine, even though I get
```
MBX-DEBUG: CLI args {'xmlid': '', 'data_dir': None, 'verbose': 2, 'format': 'svg', 'component': 'sageplot', 'server': None, 'abort': False, 'xml_file': '../src/NTIC.xml', 'stringparams': None, 'dir': '../images', 'out': None}
```
and the only two other times this shows up in the debugging info it still says `../src/NTIC.xml`, not an expanded version.  I don't believe my shell is expanding this, after a bit of experimenting.

**Comment by davidfarmer** [comment]
obsolete, due to CLI
