### ISSUE TITLE
Apple deprecating Python

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#1125]
See [this Sage-devel post](https://groups.google.com/forum/#!topic/sage-devel/gwqQxI12evU) and [this Apple announcement](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_beta_2_release_notes)

> Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. Future versions of macOS won’t include scripting language runtimes by default, and might require you to install additional packages. If your software depends on scripting languages, it’s recommended that you bundle the runtime within the app. 

So a number of places in the documentation may need additional setup instructions in the future (not sure exactly when), e.g. the aside at https://pretextbook.org/doc/guide/html/s-latex-fig.html

**Comment by mitchkeller** [comment]
Deprecating could mean we still get Python out of the box for another 10 years. I think once @daverosoff has the Windows installer all nice and done, we can ask for a list of everything that he's included and look at the best way to make something for macOS. At least until we have a fully point-and-click solution, I suspect something like MacPorts or Homebrew will be recommended, as I think that's still the best way to get `pdf2svg`. It is, unfortunately, pretty well impossible to figure out what we need to do until Apple changes something, so I'm not sure that this is an issue ripe for action any time soon.

**Comment by kcrisman** [comment]
> Deprecating could mean we still get Python out of the box for another 10 years.

It is a little unclear in the current information they are putting out; reading some of it, it seems like even putting it in the upcoming Catalina was a stretch.

> I suspect something like MacPorts or Homebrew will be recommended

Yikes.

> I'm not sure that this is an issue ripe for action any time soon.

Absolutely, but I think it's important to have a placeholder for it.  Ideally, we will have people who know even less than I do about programming coming to the world of PTX, and keeping this in mind for the future is one way to do so.

**Comment by mitchkeller** [comment]
> > I suspect something like MacPorts or Homebrew will be recommended
> 
> Yikes.

Why "Yikes"? I believe it's also still the best route to getting `pdf2svg` onto a Mac. Unless Apple decides to totally take away the terminal, it will be very easy to provide a short list of commands that one can execute in order to install everything one needs to build PreTeXt. In fact, I think we could probably even get an essentially empty package that just has all the things PreTeXt needs as dependencies into one of those repositories and then it would be one command to install MacPorts/Homebrew and another one to get all the things PreTeXt relies upon.

I'm not opposed to a pointy-clicky installer on macOS if someone is inclined to make one, but there is a viable route that requires minimal work.

**Comment by kcrisman** [comment]
> Why "Yikes"?

I find both of these to be more labor-intensive than installing the command line tools.  (Also, since at least one installs into `opt` it sometimes conflicts with other stuff, from what I hear.)  But since I only use Sage to generate images I probably don't need `pdf2svg`.

> In fact, I think we could probably even get an essentially empty package that just has all the things PreTeXt needs as dependencies into one of those repositories and then it would be one command to install MacPorts/Homebrew and another one to get all the things PreTeXt relies upon.

That would be great.  I don't think one needs point-click, at least not until we get a GUI interface for running `xsltproc` and `mbx`.  But just a few commands is best, and explicit ones that are time-tested - no sending people off to newsgroups 😄

**Comment by kcrisman** [comment]
Anyway, if/once that is the case, then that could take care of this issue as well, but for now we can just have it to await some eventual resolution if/when that time comes.

**Comment by davidfarmer** [comment]
Obsolete, as things like the CLI take care of such matters.
