### ISSUE TITLE
bare image in remark?

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#1144]
A bare image is recently (or soon will be) a legal peer of p in many places. I'm posting an issue to track if it becomes a legal peer of p inside a remark, which has come up several times in more than one project.

**Comment by Alex-Jordan** [comment]
To be clear, an image is not currently a schema-compliant child of a remark, though it seems to work.

**Comment by rbeezer** [comment]
There is another use case to discuss (soon) that will affect schema construction.  Then this will be straightforward.

**Comment by rbeezer** [comment]
An `image` should be an allowable child of a `REMARK-LIKE` now (in addition to generally being allowed as a peer of `p`).

If not,  @Alex-Jordan, go ahead and re-open this.

It **is** in the schema, in the `BlockText` patter, which is built-up to make the `BlockStatement` pattern.
