### ISSUE TITLE
Basic file management

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext#1165]
New users who are not knowledgeable about Unix environments
need to have basic concepts explained.  If this is in the documentation,
there is not enough of it or it is not in the right place.

Here is something from an email I just sent to a new user,
obfuscated to protect their identity:

  You seem to be building the HTML in the same directory
  as the PTX source.  Make a new directory, maybe called "html",
  go into it, and then do something like

`xsltproc --xinclude ~/mathbook/xsl/mathbook-html.xsl ../index.ptx`

I also had to explain that they should not put their PreTeXt code
as a subdirectory of the repository for their book.

**Comment by rbeezer** [comment]
Maybe belongs early in this chapter:

https://pretextbook.org/doc/guide/html/processing.html

**Comment by davidfarmer** [comment]
CLI should make this irrelevant.
