### ISSUE TITLE
Extend mbx script to also produce PNG versions of images

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#129]
Self-explanatory, but motivated by larger discussion at:

https://groups.google.com/forum/#!topic/mathbook-xml-support/87HQcaJfZa0

**Comment by Alex-Jordan** [comment]
This is done now for `latex-image` (you can have svg, tex, pdf, png, or eps output formats), but still needed for other image making tools.

**Comment by Alex-Jordan** [comment]
I think this was taken care of long ago. If there is some image-making mechanism that does not offer a png option, it should be a new issue.
