### ISSUE TITLE
Numbered items in conclusions are all wrong

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#139]
With new numbering scheme at 701cc411 these are still problematic.  Seems to require a conclusion within a level `m` division when the structure number is set to have `m+1` components (iirc).

LaTeX: is brain-dead for a conclusion following a final subdivision.  There is no natural way to mark it off, so the MBX conclusion as output is simply subsumed into the final subdivision as LaTeX sees it.  Hence its number can inherit a structure number from the final subdivision and not from the parent division.   Solution 1: use an environment for the introduction and conclusion and manage counters between the two.  Messy and will not make very clean source.  Solution 2: hard-code these numbers from MBX numbering.  Undesirable, but will not be the first time.

XSL/MBX: builds a serial number with a depth first search of a subtree, so at a conclusion of a division, it counts everything in the preceding subdivisions.   Solution: Perhaps some arithmetic with counts/serial-numbers in selected subtrees of the division  (division - introduction - all-subdivision + conclusion) or (count(introduction) + serial-number(conclusion)).

**Comment by rbeezer** [comment]
I've incorporated a test case into the sample article at 4833c809, within Subsection 4 of the "Advanced Numbering" section.

**Comment by rbeezer** [comment]
Check if a numbered item has a conclusion for a parent, and that conclusion is at a deep enough level to exhibit the problem (item's level less than [equal?] numbering level).  Then *count* like items in a preceding introduction and add that to the number within the conclusion.  (Effectively bypassing the count of the intervening subdivisions.)

**Comment by davidfarmer** [comment]
Numbering is undergoing a major refactor.  Make a new issue if problems remain.

**Comment by Alex-Jordan** [comment]
I believe we are heading toward outlawing numbered items in a conclusion, so this would be moot anyway.

**Comment by rbeezer** [comment]
Still could have a footnote in a conclusion, but I think I have that sorted in base templates.  We'd need to hardcore in LaTeX since it is a bit rough there.
