### ISSUE TITLE
Implement detached proof(s)

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#141]
Suppose a proof comes way after the statement of the theorem (eg, because of intervening lemmas).

Put a `theorem="main-result"` attribute on the `proof` and `xml:id="main-result"` on the `theorem` to link them.  Then have numbering, cross-references, knowls, etc all react accordingly (in concert with a "usual" `proof` contained inside the `theorem` element).

Investigate if the inverse relationships (theorem points to proofs) is useful (likely, eg point to proofs at theorem statement) and can then be "discovered" or must be given explicitly.

This would be the time to implement support for multiple proofs.

**Comment by kcrisman** [comment]
:+1: So very typical of upper-level texts.  Oooh, multiple proofs!  Like infinitude of primes, quadratic reciprocity, Pythagorean Theorem, ...

**Comment by kcrisman** [comment]
@rbeezer I think this was long since implemented, though not with the attribute mentioned, maybe this could be for auto-detection instead of the current detached proofs.  At any rate it's in the sample article, as are multiple proofs ... and thank you very much!

**Comment by kcrisman** [comment]
Incidentally, when I tried this, it mostly works, but with a xref
```
<title>Proof of <xref text="type-global" ref="theorem-fta" />.</title>
```
I get an extra period for some reason.

**Comment by davidfarmer** [comment]
It looks like to put the period in the title markup,
which is why you see two of them.
