### ISSUE TITLE
solutions generator for project tasks in latex

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#1540]
Something is wrong with the solutions list generator for project tasks in latex. Take a look at the solution to Project 4.4 in Appendix B (currently page 179). A "(d)" seems to overstrike the "(c)".

**Comment by Alex-Jordan** [comment]
The cited example is in the sample article: https://pretextbook.org/examples/sample-article/derivatives.pdf

**Comment by Alex-Jordan** [comment]
Some investigation reveals that the "(d)" belongs to the previous enumerate. It should appear right before the *Hint* from that previous enumerate.

**Comment by Alex-Jordan** [comment]
Experimenting reveals that if I change `\item[(d)]\par\smallskip%` to `\item[(d)]\smallskip%` then the issue clears up. Running out of time today to track this all the way through, but something about using `\par` in this location is part of what's going on. So, noting for posterity.

**Comment by rbeezer** [comment]
Should be fixed now, with many unnecessary separators no longer appearing in LaTeX output.

At e390b94024603ee0f14710c3bf3e3f70112a7ec5

Provoking thread (more serious consequences) at

https://groups.google.com/g/pretext-support/c/JJ8v7PVbN0E/m/gkUIUVuAAgAJ
