### ISSUE TITLE
embedded_sagecell.js should be `defer`

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext#1660]
There should be a `defer` tag on all Javascript that is not needed right away. I believe MathJax setup code is the only code that needs to be loaded before the page.

**Comment by rbeezer** [comment]
Gave this a try for Sage Cells.  After the page loads, the cells are not visible.  But if I open (an unrelated) knowl, the cells all become visible.

@davidfarmer may be experimenting with JS right now, I see some hints in the console.  I'll try again later.

**Comment by davidfarmer** [comment]
I am not doing anything with the JS (not the JS called by the dev branch).

**Comment by rbeezer** [comment]
Darn.  ;-)  I'll post some console output once I get back to that branch.

**Comment by rbeezer** [comment]
Console errors about `knowlc`are gone now.  But behavior exists.  I can post a smaple if requested.

**Comment by rbeezer** [comment]
Adding `@defer` still makes Sage cells totally go away.  I'm closing this and it can be reopened if there is interest.
