### ISSUE TITLE
Produce and harvest QR codes for lesser reading systems

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#1670]
A QR code for a YouTube video, or one of our "standalone" pages for `interactive` is used throughout our LaTeX conversion, since PDF is not very interactive.

They would be useful elsewhere, such as in EPUB.  So having a routine in PreTeXt core to get the links, build PNG images, and stash them in a "generated" directory would be a great help.

Use some (commonly) available Python library, ideally pip-installable for the CLI, such as described here:

https://towardsdatascience.com/generate-qrcode-with-python-in-5-lines-42eda283f325

**Comment by StevenClontz** [comment]
Strong vote to do QR code generation in Python, not in LaTeX. Every build uses Python, not every build uses LaTeX.

**Comment by rbeezer** [comment]
This got underway at ebd94b8ed16f32563c085f189c495bc6bc54324d and will migrate into the static versions of `interactive`.
