### ISSUE TITLE
Remove compact-buttons option

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext#1672]
The CSS no longer supports compact-buttons, so that option and associated xsl can be eliminated.

**Comment by rbeezer** [comment]
Great!  I can do that, but is it OK to wait for the "overhaul" to wrap up?  Those buttons are likely mixed in with work that is now in several places (you, me,...).

**Comment by davidfarmer** [comment]
Yes, please wait for overhaul to finish!

I am making changes to css classes and ids and will submit issues
as I see them.

**Comment by rbeezer** [comment]
Got it.  Just checking since we are on the first step of a combinatorial explosion in workflow potential.  ;-)  Thanks.

**Comment by rbeezer** [comment]
Removed at f9ecf97f8a967d6ff96dc2da4239ef7c5bb8179d, plus two follow-on commits for the associated publisher file entry and the documentation.
