### ISSUE TITLE
Remove ids on treebuttons

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext#1673]
Remove the ids:
upbutton, nextbutton, previousbutton

Those buttons have css classes which are needed for styling.

**Comment by rbeezer** [comment]
These went away as part of the "overhaul" branch in c86b6f82661a5333b69736eb874e6a5b58a087b2.

Some stale parameter passing removed just now: d658fc893c209a8f31052b661a52fae381f7ff20
