### ISSUE TITLE
Expand "proof" to PROOF-LIKE

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#1677]
With `argument`, `justification`, and maybe more.  Suggestions?

**Comment by arechnitzer** [comment]
Something equivalent to a faulty-proof would be useful. Fallacious?

**Comment by Alex-Jordan** [comment]
`pretext` ;)

**Comment by Alex-Jordan** [comment]
`rationale`, `explanation`*, `grounds`

A false proof is a `fallacy`?

*ORCCA renames `solution` to `explanation` because of the special meaning for "solution" in a basic algebra context. But that should not matter.###

**Comment by arechnitzer** [comment]
dubiety ?

**Comment by davidfarmer** [comment]
sketch
analysis
reasoning
explanation

**Comment by arechnitzer** [comment]
I recommend avoiding "fallacy" for incorrect-proof.. since a fallacy is often a more formal thing like "affirming the consequent" or "proof by loudest voice" or similar, as opposed to an incorrect proof of a true statement.

**Comment by StevenClontz** [comment]
On one hand, for the sake of consistent design of PreTeXt, I think we're doomed to need a dozen different tags to cover every possible nuance of a proofy piece of content.

On the other hand, to quote Rob, elements are expensive, and attributes are cheap. So it's a shame that there isn't a single element to describe "proof-likes" that could be fine-tuned by an attribute to cover each flavor.

**Comment by rbeezer** [comment]
This happened, and begins at 32400d635575b518f57d228a8d5f76b63019fd67 with several more follow-on commits.
