### ISSUE TITLE
Live WW exercises not working on repo docs

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#1713]
The Guide has live WW exercises at:
https://pretextbook.org/doc/guide/html/basics-s-webwork.html
But they are not working.

Neither are those at the Showcase Article:
https://pretextbook.org/examples/showcase/html/webwork.html

My suspicion is that this has to do with Rob's build script, not something with the PreTeXt repo itself.

**Comment by rbeezer** [comment]
Known problem, been unable to investigate.

**Comment by Alex-Jordan** [comment]
Just a ping about this. It may be that I should help update the publication file for each document.

**Comment by rbeezer** [comment]
Showcase Article is fixed via #1693.  Plus new way to specify WW server in publication file.

I'm **guessing** some `*.ptx` v. `*.xml` confusion on my part is to blame for the outage.

**Comment by rbeezer** [comment]
Recent changes mean missing representations files are raising processing errors.  So I removed the two examples in the Guide at 8e2c030c7e5288c8eb2072af90d510561e7dca8d.  That change can be easily reverted.

**Comment by rbeezer** [comment]
Content in the Guide is back.  Still not building, but there is no longer a processing failure.  These WW were not to blame, I'd introduced a bug, which is corrected at fb3fc82cfc28a80a156e3d00ddf286656a595d99

**Comment by rbeezer** [comment]
PR #1740 fixes this for me locally, but I may still need to adjust my build script.  Closing now and will get it straight shortly.
