### ISSUE TITLE
pretext-solution-manual-latex.xsl sets latex.print

### ISSUE THREAD

**Issue by mitchkeller** [PreTeXtBook/pretext#1726]
Anyone using pretext-solution-manual-latex.xsl is automatically getting hit with a deprecation warning because it sets the latex.print stringparam. @rbeezer said that this stylesheet should really be setting the latex-print variable to yes instead.

**Comment by rbeezer** [comment]
Worse, some defaults (one-side/two-side, color, etc) are different for the electronic/print dichotomy and were not what they should have been.  Overriding the correct boolean variable from the `publisher-variables.xsl` stylesheet has corrected that.  There are individual settings for some of those, which you can set now if you do not like the new defaults.

Thanks very much @mitchkeller.

Code at 6a6f87b20c1018724c5f6264a4065bc6c97d3d78, website updating as we speak.

**Comment by rbeezer** [comment]
Should have said - tested on Judson's AATA, there will be an automatic example at the website.
