### ISSUE TITLE
interactive activecode program for language=Java does not display as an activecode

### ISSUE THREAD

**Issue by bhoffman0** [PreTeXtBook/pretext#1739]
Do activecode programs only work for Python currently? 
_program xml:id="hello-world" interactive='activecode' language="java"_ does not display, although if you change it to lnguage="python" it does. They also do not display at all in a listing tag in a structured doc.
<img width="683" alt="image" src="https://user-images.githubusercontent.com/4571962/173151911-6ad7cbcd-1b9c-4654-a99d-7c659802c54e.png">

**Comment by rbeezer** [comment]
@bhoffman0  -  Have a look here:

https://pretextbook.org/examples/sample-book/noparts/html/section-15.html#p-800

which is good as documentation gets right now.  No, we don't run Java in any old browser.

(Psst: we do most support on the `pretext-support` Google Group.  Once **we know** something is a bug, then we make issues.  You might find

https://pretextbook.org/doc/guide/html/welcome.html

worth a look.)

**Comment by bhoffman0** [comment]
Ok thanks, I know it will not run on localhost, but I thought that it would display it in a box like the python one. It would be good to display it differently than a non-interactive program.
