### ISSUE TITLE
Interactive exercise documentation progress

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#1741]
This is a meta-issue to announce progress on the documentation of interactive exercise types supported by Runestone.  I expect it to have a lifetime of less than a week.

Pinging: @bnmnetp   @bjones1 @bhoffman0  @ericsonga  @davidfarmer @Alex-Jordan  @mitchkeller 

@bnmnetp   - feel free to add other Runestone authors, especially in advance of next week.

There is a  `pretext-dev` thread already, please use that for discussion, consider this announcement only.

**Comment by rbeezer** [comment]
General overview initiated at: https://pretextbook.org/doc/guide/html/topic-interactive-exercises.html

True/False for openers: 
Subsection 4.12.1: True/False Exercises 
https://pretextbook.org/doc/guide/html/topic-interactive-exercises.html#true-false-exercises

**Comment by sean-fitzpatrick** [comment]
For true/false, does the `<feedback>` only appear if the student answers incorrectly?
Or is it possible to have one feedback if the student answers correctly, affirming why their answer is correct, and another if they answer incorrectly, suggesting some aspect they need to reconsider?

**Comment by sean-fitzpatrick** [comment]
Oh, looking at the Sample Book, the feedback comes with the correct answer, but there is also a hint!

But I guess if you're not happy with the defaults for the true/false type, you can get more control using the `<choice>` markup in the multiple choice example that follows. (After all, T/F is really just MC with two choices...)

**Comment by rbeezer** [comment]
Thanks for poking around with this, Sean.

> There is a pretext-dev thread already, please use that for discussion, consider this announcement only.

If you ask about feedback on the `-dev` "sneak peek" thread, I'll supply some rationale.

**Comment by rbeezer** [comment]
Multiple-choice, Parsons problems, and matching are now documented.

https://pretextbook.org/doc/guide/html/topic-interactive-exercises.html

**Comment by rbeezer** [comment]
Subsection 4.12.7: Coding Exercises and Projects 
https://pretextbook.org/doc/guide/html/topic-interactive-exercises.html#coding-exercises-projects

Subsection 4.15.2: Interactive Programs, CodeLens 
https://pretextbook.org/doc/guide/html/topic-program-console.html#interactive-program-codelens

Subsection 4.15.3: Interactive Programs, ActiveCode 
https://pretextbook.org/doc/guide/html/topic-program-console.html#interactive-program-activecode

@bnmnetp  can you give the table in Subsection 4.15 a very close look?
Subsection 4.15.4: Interactive Program Capabilities 
https://pretextbook.org/doc/guide/html/topic-program-console.html#subsection-68

Code for "Coding Exercises" needs to catch up slightly with what documentation says.

**Comment by rbeezer** [comment]
Done with major push for documentation (and mostly for code).  There may still be some small changes.  But this issue is now retired.

Please continue to use the `-dev` "Sneak Peek" thread for comments, changes, corrections, etc.  Possible I will make a `-announce` announcement soon and/or start a new thread on `-dev`.
