### ISSUE TITLE
epub script tries to install outdated version of speach-rule-engine?

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext#1753]
In `scripts/mjsre/package.json` the dependency for `speech-rule-engine` is 4.0.0-beta.2.  However, it looks like the most recent release is 4.0.6.  I'm pretty sure when I `npm install` from that folder, I'm not getting any speech-rule-engine.  So first, should this be updated?  And second, can the version be set so that if a beta is not available any more, we still get something?

**Comment by rbeezer** [comment]
This is all fixed-up by #1770 and worked very smoothly for me.
