### ISSUE TITLE
Add blank line before box line

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1793]
Boxes should be preceded by a blank line, **unless**:
"Do not leave a blank line between boxed material and any accompanying heading, caption, directions, or source citation."

**Comment by rbeezer** [comment]
Liblouis allows for a style to specify the number of blank lines before or after an object.  After works great.

Before seems to insert the lines **after** the top box line.  Which is no good.

Perhaps I'll ask on their mailing list?

**Comment by rbeezer** [comment]
`liblouisutdml` is unable to fix.  See https://github.com/liblouis/liblouisutdml/issues/90

So #1861 should now have it under control and can close this.
