### ISSUE TITLE
Free standing numbers in narrative text

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1794]
I found some free standing numbers that were transcribed in Nemeth. 
Nemeth UEB Manual Section 2.3: Free standing numbers in narrative text should be transcribed in UEB to avoid excessive code switching. When such numbers are touching literary punctuation such as quotes or parentheses, they are still considered to be "freestanding" and may be brailled in UEB.

**Comment by rbeezer** [comment]
I've got this under control now.  Not yet public, it is part of the bigger inline math work.

**Comment by rbeezer** [comment]
Now public.

In  c9308102310b2e621b577ba7f9acd650f46af770  search on `&DIGIT;` to see where this case is handled.
