### ISSUE TITLE
Hypothesis options syntax error

### ISSUE THREAD

**Issue by grady** [PreTeXtBook/pretext#1796]
There is a syntax error in the JSON used as the default Hypothes.is configuration options. The object elements are incorrectly separated by semicolons `;` which should be commas for valid JSON. (Lines 12261-3)

 Also, `openLoginForm` does not seem to be a [supported option](https://h.readthedocs.io/projects/client/en/latest/publishers/config/) for the Hypothes.is client.

In general, it might be nice to have the options block be user-configurable instead of hard coded.

https://github.com/PreTeXtBook/pretext/blob/3899672f474f0251ddec004ef31efd8bb5567153/xsl/pretext-html.xsl#L12254-L12268

**Comment by rbeezer** [comment]
Thanks, Grady.  That is old code!  ;-)  At a braille workshop right now, so will try to get to this once I return home.

**Comment by rbeezer** [comment]
Changes made at 9550048a9986180c13db91ac7206ffefd12acf43

Can you build some HTML output, test, and report?

I've put the feature request onto #1800.

Thanks for the very careful report.
