### ISSUE TITLE
Keeping Nemeth indicators on the same page

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1797]
The following question was asked during the workshop.
If an expression is so long that it ends up split across lines, can we ensure that the Nemeth indicators appear on the same page as the content. Example, with a 40-character expression, the open Nemeth indicator is placed on the previous line of text, the expression is placed on the following line, and the closing Nemeth indicator is placed on the following line. There is a risk that one of these indicators will appear on a different braille page than the expression and the other indicator. 
**Nemeth UEB manual:
2.5.3 Switch Indicators at Page Turns:** If the switch to Nemeth Code occurs at a braille page turn, keep the opening switch indicator on the same braille page as the mathematical material to which it applies.

**Comment by rbeezer** [comment]
Display math is being controlled by a `liblouis` style

```
style displaymath
  firstLineIndent 0
  dontSplit yes
```

Inline mathematics can (will) cross several lines quite frequently, so we will need to try some similar HTML element and class (`inline-long`?), along with a style when we **know** the braille is greater than the available width, less 6.

**Comment by rbeezer** [comment]
As of 2184b851475ff1952a7c8fb53b375d5a8f286535 almost all math, with indicators, is in a group which liblouis will not split across page.

There is one danger case, noted in the code: authored as inline math, with Nemeth proper having a length of between 35 and 40 characters.  To make this appear inline as naturally as possible (and consume one less line than an alternative) we run the risk of the two or three lines crossing a page bounday.  I'm going to close this, but after discusiion we can make a new, more targeted, issue.
