### ISSUE TITLE
Support for circuitjs interactive elements

### ISSUE THREAD

**Issue by stevenbell** [PreTeXtBook/pretext#1815]
I'm writing a book where I make extensive use of the Falstad circuitjs library: http://www.falstad.com/circuit/circuitjs.html

I'm able to insert an `iframe` into the PreTeXt source like so:

    <interactive xml:id="interactive-circuitjs-iframe" iframe="circuitjs/circuitjs.html?cct=$ 1 0.000005 10.20027730826997 58 5 50 5e-11%0AR 464 32 464 -16 0 0 40 3.3 0 0 0.5%0Ag 464 224 464 240 0 0%0As 464 128 464 224 0 1 false%0Ax 351 82 436 85 4 12 pullup\sresistor%0AO 464 128 352 128 1 0%0Ax 268 130 321 133 4 12 input\spin%0Ar 464 32 464 128 0 10000" label="interactive-sage-jupyter-iframe" />

But ideally, I would be able to write the circuit description directly in the PreTeXt source without having to glob everything into the URL string:

    $ 1 0.000005 10.20027730826997 58 5 50 5e-11
    R 464 32 464 -16 0 0 40 3.3 0 0 0.5
    g 464 224 464 240 0 0
    s 464 32 464 128 0 0 false
    s 464 128 464 224 0 1 false
    x 274 181 431 184 4 12 bottom\sswitch\s(to\sground)
    x 312 85 426 88 4 12 top\sswitch\s(to\sVdd)
    O 464 128 544 128 1 0
    x 532 110 593 113 4 12 output\spin

This would get converted into the URL query string needed for the `iframe`.  I've written a tiny Sphinx/Runestone module to do this; it uses the following code which just replaces newlines with the HTML-escaped newline character and `' ' ` with `'+'`:

    # content is an array of strings, one element for each line
    # Join them back together with the URL-escaped newline character
    circuittext = "%0A".join(self.content)
    circuittext = circuittext.replace(' ', '+')

    text = '<div class="circuitcontainer"><iframe id="circuitFrame" width=800 height=550 src="/_static/circuitjs.html?cct=' + circuittext + '"></iframe></div>'

I'm actually not sure that the space-to-plus substitution is necessary --- it seems to work without it currently  But I don't know enough about how browsers/javascript/etc work to say either way with certainty.

**Comment by rbeezer** [comment]
Thanks for your patience, @stevenbell, I lost track of this one for a while.

Implemented, see

Subsection 14.8: CircuitJS 
https://pretextbook.org/examples/sample-article/html/section-interactive-authored.html#subsection-59

and then look at source of sample article to see how to make it happen.

Very conveniently, the XSL processor does a great job of escaping the code for use as a URL string, so your script seems to happen with no extra effort.

Of course, this provokes questions:

* Where is this language documented?  I couldn't find it.  It'd be good to provide a link.
* Are there options to modify the widget's appearance?  Like killing the menu bar. (Which might not be of interest?)

**Comment by rbeezer** [comment]
I'd been hoping for some follow-up on this one, now that it is implemented.  I'm going to close now, but it can be re-opened.
