### ISSUE TITLE
Feature request: add xtermjs 

### ISSUE THREAD

**Issue by pearcej** [PreTeXtBook/pretext#1817]
This Feature Request was recommended by @bnmnetp
 Support for https://xtermjs.org/docs/ as a component is needed to allow for interactive Linux windows.
 The API looks reasonable, and I am happy to help.

**Comment by bnmnetp** [comment]
Jan, 

Are you sure you are not talking about this:  https://bellard.org/jslinux/. It has a shell and a small implementation of linux that includes git.  I don't see how to make xtermjs do anything unless it is used to log into a real system somewhere.

I think a good place to start with this on pretext is to with an interactive -- see https://pretextbook.org/examples/sample-article/html/section-interactive-authored.html

The code for one of these looks like:

```xml
<interactive xml:id="interactive-simple-eigenvector" platform="javascript" width="60%" source="code/austin/figures.js code/austin/simple-ev.js" preview="preview/simple-eigenvector-preview.jpg">
     <slate xml:id="eigenvector" surface="canvas" />
     <instructions>
     <p>Let <m>\vec{x}</m> be represented by the red arrow, and <m>A\vec{x}</m> by the grey arrow, for some particular <m>2\times 2</m> matrix <m>A</m>.  Drag the <em>tip</em> of the red arrow to see the grey arrow change.</p>
     </instructions>
</interactive>
```

PS - unlike the Runestone community, the PreTeXt community typically discusses new ideas on the pretext-dev mailing list.   When something is ready for implementation then the discussion moves to Github.

**Comment by pearcej** [comment]
@bnmnetp Yes, I agree and thanks for the pretext-dev community tip.  Will do.

**Comment by rbeezer** [comment]
@pearcej - will you be putting this out for discussion on `pretext-dev`?

**Comment by pearcej** [comment]
@rbeezer yes, thanks for the suggestion. I can also come to the drop-in session.
