### ISSUE TITLE
Transcriber notes

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1823]
We're currently using transcriber notes to inform the reader when a page needs to be removed from the BRF file and replaced with a tactile graphic. The formatting should be updated to reflect BANA standards. The words "transcriber note" do not need to be included, as this information is indicated by the transcriber note indicators.

Transcriber's notes that contain 7 or fewer words can be embedded within text. We do not currently use this style of transcriber's note. 

Transcriber's notes begin on a new line, following the margins noted below. 

Reference: [BANA Formats 3.2.1](https://www.brailleauthority.org/formats/2016manual-web/section03.html)
- A standard transcriber's note uses **7-5 margins** and provides information to the reader before the affected text. 
- Unspaced transcriber's note indicators begin (`.<) [dot 4, dot 46, dot 126] and end (`.>) [dot 4, dot 46, dot 345] a transcriber's note, regardless of the number of paragraphs or items it may contain.

**Comment by rbeezer** [comment]
Implemented as a template for consistency, and being used with images.

14aa6d501e4eac814db4fe54be3833fa3f7a0720

Thanks, @mcantino1 for the careful instrucions.
