### ISSUE TITLE
Boxes within Boxes

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1825]
Boxes within boxes require a special format to help the reader better track the outer and inner boxes. 

Issue found in AATA: Example 4.7, contains an inner box with an image description. 

Reference: [BANA Formats 7.6.1](https://www.brailleauthority.org/formats/2016manual-web/section07.html#_Toc462410904)
- Exterior box uses a full-cell [dots 123456] across the page for the opening and closing exterior box lines
- see reference for additional details regarding use and non-use of blank lines when opening and closing boxes

**Comment by rbeezer** [comment]
This will typically happen when a FIGURE-LIKE is placed within another block.  So perhaps:

* a style for the exterior box using the "bigger" cells.
* a conditional in the XSL to look for descendants and switch the class name accordingly
* the interior boxes would be unaffected, they could retain current behavior everywhere

**Comment by rbeezer** [comment]
And with boxes now more under our control, this was much easier.  Handling of proofs is odd to my sensibilities, but we need to follow the HTML for now.

At: 0ee9dcbd0589446840603295f1cc87f469ab1981

Thanks, @mcantino1, I might not have even known this was a thing!
