### ISSUE TITLE
Missing bust menu on mobile

### ISSUE THREAD

**Issue by bnmnetp** [PreTeXtBook/pretext#1831]
I was checking on some things with my phone and could not find the User menu.

**Comment by bnmnetp** [comment]
Tagging @davidfarmer 

I know there is not much space to work with but without the bust menu students can'd get to import elements of the course.

**Comment by davidfarmer** [comment]
I think what we need is to have it appear when the TOC
is brought up in mobile.  I'll see what I can do.

**Comment by rbeezer** [comment]
A job for the overhaul branch?

Likely worth discussion on pretext-dev.  As to placement.

**Comment by davidfarmer** [comment]
I think I fixed this during a drop-in.

**Comment by rbeezer** [comment]
I think GH messed up the ttiming on these messages.

No matter, I checked the Sample Book, hosted on Runestone, with a super-skinny browser width to provoke mobile interdace.  Bust is a button in the upper-right.  So closing...

**Comment by Alex-Jordan** [comment]
> I think GH messed up the timing on these messages.

There's been a lot of that this week. I think three times with APEX, one with a message that someone originally posted back around May.
