### ISSUE TITLE
Binomial Notation Nemeth

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1845]
Nemeth in UEB manual 12.7.1 Binomial Coefficient

In Nemeth, binomials are not spatial. They are written on a single line with a "directly under indicator" (ASCII %) between the items. Example: (n%q)
Example: (n-1%K-1)

**Comment by rbeezer** [comment]
Noted upstream at SRE repository:

https://github.com/Speech-Rule-Engine/speech-rule-engine/issues/686
