### ISSUE TITLE
runestone-manifest.xml has wrong runestone version

### ISSUE THREAD

**Issue by bnmnetp** [PreTeXtBook/pretext#1848]
Rob,

Testing out the latest changes httlacs on the dev server and the book is broken.

The latest version of runestone is 6.3.18 - the book builds and puts in the links to the correct 6.3.18 files, but the manifest is written to say that the version used was 6.3.16
So I don't update the files in _static and the components do not work.

**Comment by rbeezer** [comment]
Try now.  Pull and use the most recent for a build.  Report back?

**Comment by bnmnetp** [comment]
Yes, that fixed it on my local installation.

Thanks for the quick turnaround.
