### ISSUE TITLE
Community links on PreTeXtBook.org

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext#1853]
Suggested update to the social media stuff on PreTeXtBook.org (note the `rel="me"` for Mastodon verification)(:

```
Connect with the <a href="https://twitter.com/hashtag/PreTeXtGang">#PreTeXtGang</a> on
<a href="https://twitter.com/PreTeXtBook">Twitter</a> or
<a rel="me" href="https://fosstodon.org/@PreTeXt">Mastodon</a>.
```

<blockquote>
Connect with the <a href="https://twitter.com/hashtag/PreTeXtGang">#PreTeXtGang</a> on
<a href="https://twitter.com/PreTeXtBook">Twitter</a> and
<a rel="me" href="https://fosstodon.org/@PreTeXt">Mastodon</a>.
</blockquote>

**Comment by rbeezer** [comment]
Got it!  Thanks.  I diodn't know we had fled to Mastodon!  ;-)

In the local code, will appear on next big website update (usually several times a day).

**Comment by bnmnetp** [comment]
Did twitter take away our blue checkmark?

**Comment by StevenClontz** [comment]
🤣 I just figured it didn't hurt to grab a nice @PreTeXt handle on a reasonable server in case Twitter becomes the next MySpace in the coming months. I'm continuing to keep up with our Twitter presence as well (need to find a cross-poster).
