### ISSUE TITLE
Braille Boxes and the Keep-Together Rule

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1862]
Braille boxes should be kept on a single page whenever possible. Boxes should not break across pages if the box could be presented on a single page. Boxes should be moved to a new braille page where necessary. 

If the box could not fit on a single braille page, then that box does not need to be moved

From [BANA Formats](https://www.brailleauthority.org/formats/2016manual-web/section07.html):
**7.3.1 Placement of Boxes.** "Whenever possible, keep boxed material on a single braille page."
**7.3.5 Dividing Boxes Between Braille Pages**
a.  A top box line must be followed by at least one line of text on the braille page. If the box line is followed by a heading, the heading must be followed by at least one line of text.
b.  A bottom box line must be preceded by at least one line of text on the braille page.

**Comment by rbeezer** [comment]
Thanks for this, @mcantino1 .  Especially having the BANA rules helps a lot.  Al was all over it, too.

All material on one page: 27a88d4d8dfb11f64b4062d2df0ba4e4bd9b37d8

Increases AATA by 100 pages (from about 1300).

Box lines: 90a2e3204c9103aa3f313b98c0628d684881ae03

We able to control top box lines at the bottom of a page, but liblouis seems to lack control at the other end (7.3.5b).  There is now a comment in the right place in the code, so I'm going to close this, even if only two-thirds successful.
