### ISSUE TITLE
Ensure managed directories can function with CLI without a publication file

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext#1872]

**Comment by oscarlevin** [comment]
We have a few possible paths forward with this.  

1. Modify core pretext to default to the same default managed directories structure as the CLI would use with the default publication file.
2. Simply remove the requirement of managed directories for the CLI (not sure what would have to be done or what the results would be).
3. Modify the CLI to create a default publication file for any target that doesn't specify one (and put that path into `project.ptx`, or tell the user to do so).

I'm leaning to 3, but would be interested in hearing @StevenClontz and @rbeezer weigh in.

**Comment by StevenClontz** [comment]
Maybe we could do this variation(?) of 3, since (I think I recall) all our work on a project happens in a temp directory:

- When a publication file is not present, silently copy our default publication file into the default location within the temp directory, and pass that on to core pretext.

**Comment by oscarlevin** [comment]
This is definitely fixed in 2.0.  We can close this.
