### ISSUE TITLE
`sfrac` is back in the MathJax config

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext#1897]
the `startup: { ready() {...}}` function was completely removed in overhaul. It initialized `sfrac`, whose support was removed. It seems to be back in main.

**Comment by rbeezer** [comment]
Well, that sounded surprising, and not in a good way.  But I'm not seeing the same as you.

Speculation: you are on a branch that needs to be rebased, or have master merged in?  You said "main" - we have only "master".

`git log -S sfrac` shows f7de3588dec14b155b47862587b959815ea45b2b as the second most-recent commit in the search results.  (The most recent is example use.)  That shows the change you reference.

I'm on 12863f2d02678fceb1219b69caaba774a6e17a67 as the tip/master.  And all the `sfrac` in  pretext-html.xsl  are the downgraded versions.

**Comment by siefkenj** [comment]
Hmm. Let me investigate. I am downloading from https://codeload.github.com/PreTeXtBook/pretext/zip/refs/heads/master

I deleted all of my precompiled directories and re-ran pretext and now everything looks good :-). Perhaps the issue is that some file names changed and I was only looking at the old files...
