### ISSUE TITLE
`typeset: false,` missing closing bracket when compiling with `react` flag

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext#1898]
When compiling for React, `startup: { typeset: false }` should be set in the mathjax config. This setting isn't getting set (it was correct on overhaul).

**Comment by siefkenj** [comment]
My mistake! This looks like it is set correctly :-).

**Comment by siefkenj** [comment]
@rbeezer  It turns out this isn't "missing", but there is a Javascript syntax error. There is a missing close brace after the `typeset: false,`

**Comment by rbeezer** [comment]
Pushed a change at: 522d4a0a6453c5d2c451de171ab385712fbd0a53

That brace should function for both stanzas of the "choose" now.  I tested "regular" HTML, could you confirm the fix for React situation (and then close this)?

Thanks for pointing this one out!

**Comment by siefkenj** [comment]
Looks good.
