### ISSUE TITLE
Braille: Image Description vs Caption Formatting

### ISSUE THREAD

**Issue by mcantino1** [PreTeXtBook/pretext#1900]
[BANA 6.3](https://www.brailleauthority.org/formats/2016manual-web/section06.html#6-3)

Captions

- Captions use a 7-5 format.
- If the image is identified as a “Photograph” or a “bar graph”, that descriptor is enclosed in transcriber note (TN) indicators and is then immediately followed by the caption. In the BANA example, the word "Photograph" is enclosed in TN indicators and is then immediately followed by the caption text "Views of anger ..."

Description

- An image description follows a caption and begins on a new line
- Image descriptions use a 7-5 format and are enclosed in transcriber note symbols

**Comment by rbeezer** [comment]
Descriptions follow captions already now in new work as transcriber notes.  Authors never identify images as Photographs or bar charts, so we have no need to implement that.

We generalize a "caption" on "Illustrative Material" to include a title on a table or our `list` block (which is not a list itself, but does **hold** a list).  7-5 margins now via 49b6569fc697733cea093afd581c8cc7c26cf7dd
