### ISSUE TITLE
Ensure annotated sample article contains escaped source

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext#1936]
In e.g. [Figure 9.4](https://pretextbook.org/examples/sample-article/annotated/graphics.html#figure-tikz-electronics) of the Sample Article, a `<` character in the "View Source" fails to be escaped as `&lt;`.

**Comment by rbeezer** [comment]
The modal `serialize` template in `pretext-common.xsl` probably needs two modes (a parameter).  HTML for consumption by a browser and XML for viewing as how a "text" vesion of how source should be authored.

Might be as simple a matter in the latter case to convert `&` to `&amp;` in every single case, effectively breaking every escape sequences into a literal versions.

**Comment by kcrisman** [comment]
> In e.g. Figure 9.4
> <https://pretextbook.org/examples/sample-article/annotated/graphics.html#figure-tikz-electronics>
> of the Sample Article, a < character in the "View Source" fails to be
> escaped as &lt;.
>

I noticed that a few days ago, but assumed it was intentional.  In fact,
the CDATA markup also disappears currently.

**Comment by rbeezer** [comment]
> In fact, the CDATA markup also disappears currently.

CDATA **always** goes away as part of the XML parsing.  *Nothing* can be done about that as far as I know (except to perhaps convert it back, but you wouldn't know when it was used and when it wasn't).

And we try to de-emphasize its use.  It confuses a lot of principles and a lot of people.

**Comment by kcrisman** [comment]
Got it.

> And we try to de-emphasize its use. It confuses a lot of principles and a
> lot of people.
>
True!  I definitely prefer the explicit &lt;

**Comment by rbeezer** [comment]
Done.  Pushing up a test to the website now.

Dual-purpose template: 70658bd2230b9097fc941683bd780fcac8f318e1

And employment: 7be4de446f231cdf46d8c82f819e5835816e2252

Good catch - thanks!
