### ISSUE TITLE
<noscript> tag included in incorrect location

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext#1942]
It appears that two identical(?) `<noscript>` tags are inserted into pretext-generated HTML. The particularly problematic one is the child of `<head>`, since `<noscript>` elements in `<head>` are only allowed to have specific children: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript

It looks like only the `<noscript>` tag in `<body>` should be preserved.

**Comment by rbeezer** [comment]
Yep, I found the duplicate use of the `statcounter` template yesterday while waiting on a build and didn't get back to this right away.

Sloppy.  ;-)  But likely a hangover from the overhaul branch. 

Thanks for #1947.
