### ISSUE TITLE
self-reference for installing CLI

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#1943]
https://github.com/PreTeXtBook/pretext/blob/master/doc/guide/author/processing.xml#L55 says that `Instructions for installing this command line interface can be found in <xref ref="processing-CLI"/>.` But that is the very section in which this quote is found.

**Comment by kcrisman** [comment]
I looked into fixing it, but discovered that there is only https://pretextbook.org/doc/guide/html/windows-cli.html which, while having instructions toward the very end that can be adapted for non-Windows environments, isn't (yet) canonical.  If there are any obvious suggestions that are canonical, I can probably make a PR pretty easily, but didn't want to do something wrong.

**Comment by oscarlevin** [comment]
This got moved around when @StevenClontz and I rewrote the intro chapters to recommend CodeSpaces.  I'll look into finding the original guide entry from before that commit and move it into section 5.2.

**Comment by oscarlevin** [comment]
This should be closed now; see #1945
