### ISSUE TITLE
Pre-Rendering Math in Titles

### ISSUE THREAD

**Issue by Jahrme** [PreTeXtBook/pretext#196]
Looking at the HTML version of the Sample Article I noticed that MathJax has to render any mathematics in titles each time a page is loaded (just like any other mathematics) and so each time the user goes to a new page any math in titles flashes to the LaTeX code before re-rendering. I was wondering (and this is of no immediate importance) if there would be a way to have mathematics in titles be pre-rendered (possibly as SVGs) so that the navigational side bar and titles are not flashing back and forth between LaTeX and rendered math at each naviation.

**Comment by rbeezer** [comment]
Selective application of the `mathjax-node` scripts might make this happen.
