### ISSUE TITLE
"Best practices" for adjusting pdf output

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#1996]
The discussion at [this pretext-support post](https://groups.google.com/g/pretext-support/c/hS2Mi0bk3N0) has a number of interesting suggestions for how one might post-process a LaTeX file to make it look better.  This issue is for creating a (short) section for authors or publishers on some ideas for how to accomplish that routinely, as well as suggestions for the most common edits of this type.

**Comment by rbeezer** [comment]
Closed via #2216
