### ISSUE TITLE
Skip footnote creation of URLs in footnotes completely

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#1998]
Currently, a URL (with content) in a footnote creates a footnote for the URL.  This is already warned against (with workaround) in [the guide](https://pretextbook.org/doc/guide/html/topic-url.html#p-765) but in [this -dev discussion](https://groups.google.com/g/pretext-dev/c/7VlJ7-IQXL0) it seemed better to just change -assembly to disallow its creation completely.

**Comment by kcrisman** [comment]
See #1999

**Comment by rbeezer** [comment]
Closed via #1999
