### ISSUE TITLE
index hyperlinks in pdf link to wrong page

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#2007]
In commit https://github.com/PreTeXtBook/pretext/commit/ac44e87b954200b3c2569497a5d2a204a8f12630 the hyperref links were changed in style to avoid some issues with books with parts (perhaps among other things).

Unfortunately, that breaks links in hyperref from the index in electronic pdf.  The page numbers are correct, but e.g. page 65 has a link to the 65th page of the pdf, not page 65 in the numbering as before.  References to the front matter (which worked before) now don't do anything at all when you click on them.  (Note that other page number hyperlinks, such as <notation-list />, seem to work correctly.)

**Comment by kcrisman** [comment]
Workaround for authors who really need this is simply to remove the hypertexnames line.

Links of relevance, showing the solution isn't simple, but is possible (see also the comments in the code for pretext-latex.xsl):
* https://tex.stackexchange.com/questions/201758/index-links-to-wrong-page
* https://tex.stackexchange.com/questions/599395/page-number-on-index-links-to-wrong-page
*  https://tex.stackexchange.com/questions/516267/compatibility-of-hypertexnames-false-and-indexes
* https://stackoverflow.com/questions/1455488/hyper-reference-links-in-latex-document-starts-from-the-beginning-of-the-page (hackish)

**Comment by rbeezer** [comment]
Thanks for the catch, and all the research.  The third SE post looked the most reasonable and seems to have (a) fixed the index hyperlinks, while (b) not harming other hyperlinks.  More in a minute in other places.

Code: ba3a57362f213d788a141dd77f24b90e092d0938

**Comment by kcrisman** [comment]
Glad it helped!  I won't be able to test it myself for some time, but thank you very much for the fix.  The command in question seems like it could win an obfuscated code competition, glad you understood it! 🤨

**Comment by rbeezer** [comment]
> glad you understood it!

I didn't say that!  It just looked minimally intrusive.  And it worked.  ;-)
