### ISSUE TITLE
Subfootnote behavior in separate proofs

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#2008]
If you make a separate proof for a theorem or whatever, and have a footnote in that proof, the numbering isn't even wrong - it just starts over with "a", and renders completely separately.

Minimal non-working example:
```
<?xml version="1.0" encoding="UTF-8" ?>

<pretext xmlns:xi="http://www.w3.org/2001/XInclude">

<article>
<title>Test</title>
<section>
<theorem>
<statement>This is a theorem</statement>
</theorem>

<p>Intervening text<fn>with a footnote</fn></p>

<proof>
<p>This is a proof later<fn>also with a footnote</fn></p>
</proof>
</section>

</article>

</pretext>
```

**Comment by kcrisman** [comment]
This may be because the [template](https://github.com/PreTeXtBook/pretext/blob/master/xsl/pretext-latex.xsl#L10624) doesn't  have `PROOF-LIKE` but I don't know whether that even is an existing category?

**Comment by davidfarmer** [comment]
It is bad writing to put a footnote in a proof.

Closing because there is no way this issue will ever rise to the top.

**Comment by kcrisman** [comment]
> It is bad writing to put a footnote in a proof.

Why would that be bad writing by fiat?  It might be rare, but I don't see this.  It's not disallowed in the schema.  What if there is a URL in a proof (such as to link to a preprint with more details) and that generates a footnote (I don't know whether this issue would be activated then, but for the sake of argument)?

**Comment by kcrisman** [comment]
As to an issue "rising to the top" - isn't that what the workshop was just about, *increasing* the number of developers?  This is not exactly encouraging to someone who might want to help.  Inevitably, to make things sustainable in the long term, there has to be some openness to discussion before simply closing issues.  At the very least, to have full references as to *why* something is a "bad" idea.
