### ISSUE TITLE
missing "open problem filter" in footnotes

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#2009]
[pretext-latex.xsl](https://github.com/PreTeXtBook/pretext/blob/master/xsl/pretext-latex.xsl#LL10624C95-L10624C147) has a match for `&COMPUTATION-LIKE;|&OPENPROBLEM-LIKE;|&EXAMPLE-LIKE;` (among other things) in footnotes, but the open problem piece is missing in the immediately following line, `or &COMPUTATION-FILTER; or &EXAMPLE-FILTER; `.

Since everything else in those lines is repeated very precisely, is it okay to presume this was an inadvertent miss and can be provided?  Alternately, since open problem is also missing from [the earlier template](https://github.com/PreTeXtBook/pretext/blob/master/xsl/pretext-latex.xsl#L10586), maybe having open problem is an error.

In either case, I'm happy to provide the fix.

**Comment by rbeezer** [comment]
Yes, certainly an omission.  I think I was doing open problems with a search on some other `*-LIKE` to see what to change, and forgot to also search on `*-FILTER`.  And I always forget this is a two-part drill - the mark and the content.

Yes, a fix would be welcome!

And maybe add a footnote to an example in teh sample article, to make sure it continues to behave.

Thanks for catching this.  Are you using these new blocks?

**Comment by rbeezer** [comment]
Fixed at 9322c1f6305e13b4a55d81f9397b1c206ffc6485.  Thanks very much for the catch.

I had to add an example of an `openproblem` to the sample article before I could even begin to fix this!  Eventually, I should add in a bunch of examples that @davidfarmer has been working up for testing.
