### ISSUE TITLE
worksheet at chunk level

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#2013]
If a worksheet is at the chunk level (say a direct child of a book's chapter with the default chunking scheme) then the worksheet is listed in the TOC but there is no standalone page for it. For example if its id is `worksheet-1`, the TOC wants to link to `worksheet-1.html`, but that page does not exist. (What exists is `worksheet-1-letter.html` and `worksheet-1-a4.html`).

~~Related to this, I don't think it is good that we offer the readers the A4 and US button. (Even though it is good that we are capable of providing either.) A typical student is unfamiliar with paper sizes and doesn't get what these buttons are for. Also a typical publisher is not providing one single web site to both audiences. I propose that there should be a publisher option for this (in common? so it also affects print?). And then there would just be `worksheet-1.html` with the appropriate CSS for the chosen paper size.~~

~~And/or once you arrive at the worksheet page, a button could toggle the a4/letter layout. It would not need to be so concise and we could swap out the "US" for "letter".~~

**Comment by sean-fitzpatrick** [comment]
Is this a new bug? I have a [book with worksheets at the section level](https://opentext.uleth.ca/Math3410/linear-algebra.html) and the TOC seems to go to the right place.

I do agree that it would be good to have the paper size set by the publisher.

**Comment by Alex-Jordan** [comment]
Well it's what I am seeing on a `pretext new` project. There is currently only one chapter, and that chapter has two children, a "title" and a "worksheet". There is no `xml:id` on the worksheet. In output files I get:

<img width="206" alt="Screen Shot 2023-06-26 at 2 12 31 PM" src="https://github.com/PreTeXtBook/pretext/assets/4732672/2a8c64b5-299e-4aa1-ab70-cecd9d19acef">

but the TOC link is to `worksheet-1.html`.

**Comment by sean-fitzpatrick** [comment]
Hmm. I have an `xml:id` on all of my worksheets. I wonder if that makes any difference?

I just cleaned my output directory and rebuild using CLI 1.6.0, and I am getting worksheets.

**Comment by rbeezer** [comment]
This has a (potential) bug report, and a request for a change in behavior.  Please split one off into a new issue, leave one here, and make it clear on each which is which.  Thanks.

**Comment by Alex-Jordan** [comment]
This is the bug report.

**Comment by sean-fitzpatrick** [comment]
I am trying (but so far failing) to reproduce this. My steps to reproduce:

1. Run `pretext new book` in an empty directory
2. In the source directory, `touch worksheet.ptx` to make an empty worksheet file
3. Populate worksheet with a bit of content:
```
<?xml version='1.0' encoding='utf-8'?>

<worksheet>
  <title>A Worksheet</title>
  <page>
    <introduction>
      <p>
        This is an introduction
      </p>
    </introduction>
    
    <exercise>
      <statement>
        <p>This is an exercise</p>
      </statement>
    </exercise>
  </page>
</worksheet>
```
4. In `main.ptx` add `<xi:include href="./worksheet.ptx"/>` just below the default section
5. Run `pretext build web`.

I get `worksheet-1.html`, `worksheet-1-a4.html` and `worksheet-1-letter.html`.

Do I need to adjust the chunking level somewhere?

I get the same result if I add the worksheet source directly into `main.ptx` without using `xi:include`.

I'm using CLI 1.6.0.

**Comment by oscarlevin** [comment]
I wonder if this is related to a long standing (and I think unreported) issue I have with exercises being children of chapter (actually an appendix).  If you visit https://openmathbooks.org/ecm/ecm/app_projects.html and then click on the exercises divisions, it scrolls down.  But if you click on another section first and then back to the exercises directly, it is a broken link.

**Comment by oscarlevin** [comment]
We talked about this in drop-in, and I made an example: https://math.oscarlevin.com/fictional-meme/ch-worksheets-only.html.  Source here: https://github.com/oscarlevin/fictional-meme.

We decided that the issue is two-fold: deciding whether a division is structured is done by looking for (non-specialized) subdivisions, or by checking if the subdivisions are just worksheets.  But there is also some bug with the chunking level in this second case.

**Comment by rbeezer** [comment]
@oscarlevin did a really nice job of helping us together track down some of this behavior.  I have more work to do, as the presumed fix just led to other errors.

In any event, back to the original complaint.  I will speculate that the offending `chapter`
* may have only `worksheet` as non-metadata children, and/or
* the `chapter` lacks a `section`.

@Alex-Jordan, can you confirm?

**Comment by rbeezer** [comment]
A division, consisting of entirely `worksheet` as its subdivisions, is the one exception to the two models for a division's structure.  There is an `is-leaf` template that determines if a division is terminal in the document tree (independent of any sort of chunking).

That template now properly recognizes this exceptional structure as not being a leaf, and fixes to symptoms flow from there.

Code: 9bfc2bf7e4b8f040eb997479a71901df8c252481

Build Section 33 of the sample article at chunking level 3, before and after this change, to see this in action.  Website being updated now.

Thanks to everyone for their help chasing this down - it was a bit on the subtle side.

**Comment by Alex-Jordan** [comment]
Sorry I've been absent. Local stuff and the WeBWorK release has 99% of my attention. Yes, the initiating example only had a worksheet as non-metadata children. Thanks for sleuthing it out, and again I'm sorry I couldn't dig deeper myself first.
