### ISSUE TITLE
pretext generate interactive previews fails to launch server

### ISSUE THREAD

**Issue by dbrianwalton** [PreTeXtBook/pretext#2016]
See https://groups.google.com/g/pretext-dev/c/f7MAHC0Tg-s

Python on newer Mac's seem to be executing different Python executable interpreters, causing the creation of a subprocess where the Python http.server can be running to fail.

This should be resolvable by launching the same Python interpreter as the current pretext/pretext.py script is using.

**Comment by rbeezer** [comment]
Closed via #2017.
