### ISSUE TITLE
frontmatter/colophon/website has malformed URL in PDF output

### ISSUE THREAD

**Issue by jjrsylvestre** [PreTeXtBook/pretext#2030]
I have the following in my `<frontmatter>`:
````
<colophon xml:id="front-colophon">
	<website>
		<name>Discover Linear Algebra</name>
		<address>https://sites.ualberta.ca/~jsylvest/books/dla.html</address>
	</website>
	<website>
		<name>GitHub source code repository</name>
		<address>https://github.com/jjrsylvestre/dla/</address>
	</website>
</colophon>
````
In the PDF output, when I hover over the link in my PDF viewer (or right-click on the link and choose "Copy Link"), I get a link that looks like
````
https:\protect /\penalty \exhyphenpenalty {}\protect /\penalty \exhyphenpenalty {}sites.ualberta.ca\protect /\penalty \exhyphenpenalty {}~{}jsylvest\protect /\penalty \exhyphenpenalty {}books\protect /\penalty \exhyphenpenalty {}dla.html
````

**Comment by rbeezer** [comment]
I see the same thing in the Sample Book (chapters only version) as an electronic PDF at the Examples section of the website.

* Clicking on the link takes me where it should go.
* Doing a "Copy" (not "Copy Link Address") also pastes the visible content correctly (which is not the full URL).

**Comment by rbeezer** [comment]
Seems like the `address` element is being hit with `apply-templates`, and thus the text is being sanitized (literal slashes becoming `\slash{}`) and thus perhaps some extra care by hyperref to deal with those. 

* `value-of` for `address` should work better
* The URL should really be in a `@href` attribute to prevent any attempt to use XML in it.  And then it won't get sanitized either.  Rookie mistake from long ago.  So maybe the pre-processor can handle this change.

**Comment by jjrsylvestre** [comment]
Oh, I see that what I suggested is effectively what you suggested in your comment on #2031. ;)

**Comment by rbeezer** [comment]
Thanks for catching this!  Small FUBAR means some big improvements.  ;-)

Initial work at a65e151d376f7bc99220aff20fd838a9e7ffddd8 with consequences in later commits.  Announcement in a minute.
