### ISSUE TITLE
frontmatter/colophon/website needs URL in print-version PDF

### ISSUE THREAD

**Issue by jjrsylvestre** [PreTeXtBook/pretext#2031]
`frontmatter/colophon/website` gets rendered as
````
Website: Name
````
(where `Name` is the text content of the `<name>` child of the `<website>`).

In electronic-version PDF, this is fine because `Name` becomes a hyperlink. But in print-version PDF, the content of the `<address>` child of the `<website>` should also be provided somehow. Could be as simple as adding
````
    <xsl:if test="$b-latex-print">
        <xsl:text> (\url{</xsl:text>
        <xsl:apply-templates select="address" />
        <xsl:text>})</xsl:text>
    </xsl:if>
````
to `<xsl:template match="frontmatter/colophon/website" >` in `xsl/pretext-latex.xsl`, or maybe adding the URL as a footnote as is done for `<url>` content.

(Note that the XSL code above won't actually work currently, because `<xsl:apply-templates select="address" />` will output the same malformed URL as described in #2030.)

**Comment by rbeezer** [comment]
We provide this facility (in all formats) via a footnote.  So if the pre-processor were to also produce a typical/normal/universal PreTeXt `url` element, then we would get this for free.  Related discussion on #2030.
