### ISSUE TITLE
Script to accelerate startup for newcomers

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#206]
A wishlist item. Some script you run. It asks for basic info like names, institution, etc. It asks for titles (for book and chapters). Once finished, the user has a git repo located parallel to mathbook/, named according to the book title, with folder structure for a book laid out, mainfile, bookinfo, frontmatter, and chapter file skeletons all there. Basically something you can run xsltproc on, and have an empty skeleton of a book with some amount of the frontmatter and bookinfo already filled out. All files have commented copyright claims in them with the author names.  Also, a basic functioning Makefile sitting there.

I shouldn't put out these ideas and not follow through with execution, but writing scripts is not my forte. With something like this, it would make it a lot easier for newcomers to get the ball rolling without direct help from someone who already has MBX experience. I've witnessed people be excited to use MBX, but then get completely discouraged by having to learn Linux, git, XML basics for sectioning, the relevance of bookinfo and frontmatter, and xsltproc. All before they get to dive in to the content of a project.

**Comment by davidfarmer** [comment]
CLI
