### ISSUE TITLE
styling for th in HTML

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#2060]
There are various classes we put on `td`, for example `l` for left-aligned, but several more. Relatively recently (about a year ago?) we started also having `th` in tables too. They are written with these classes, but the CSS is only acting on the `td`, not the `th`. Can we (as carefully as need be) extend these CSS selectors to include `th`?

**Comment by rbeezer** [comment]
This is a pure CSS proposal, no?

If so, should it be against the "css_core" reposirory?
