### ISSUE TITLE
Typo in image folder name in 3.7 Images of the Pretext Guide

### ISSUE THREAD

**Issue by pearcej** [PreTeXtBook/pretext#2073]
In attribute of tag description, it is listed as **_ch2-images_**, but in the description of the folder it is **_c2-images_**.
![image](https://github.com/PreTeXtBook/pretext/assets/1608025/ab36e726-9922-41cc-8304-d2a6892081d8)

**Comment by rbeezer** [comment]
Thanks, @pearcej - that needs fixing.  And I try to discourage using numbers in ids, so that "ch2" needs to go anyway.  I'll make a change and report here.

**Comment by rbeezer** [comment]
Patched up at 15a4d9ba2f584f03681d3b5142598a6f73d761e6

Thanks again for the alert, @pearcej!

**Comment by pearcej** [comment]
@rbeezer Thanks for your amazing responsiveness!
