### ISSUE TITLE
Image description and shortdescription tags not both used in web build

### ISSUE THREAD

**Issue by pearcej** [PreTeXtBook/pretext#2074]
I have been testing the web build using both the `shortdescription` and `description` tags as described in section 3.7 IMages in the Author Guide (https://pretextbook.org/doc/guide/html/overview-images.html).

However, testing using `shortdescription` either alone or in combination with  `description` has no impact on the rendered HTML. 

Is this a planned enhancement or is the guide in error?

**Comment by sean-fitzpatrick** [comment]
This documentation was part of #2056 which was merged only 19 hours ago!

It should work if you're building PreTeXt directly from GitHub and have pulled before building. But I assume it'll take more than 24 hours for this to make it into the CLI.

**Comment by oscarlevin** [comment]
These changes should be in the CLI nightly (2.0.2.dev20230919) which you can get by upgrading with `pip install pretext --upgrade --pre`).  I'll probably make a stable patch release Friday.

**Comment by rbeezer** [comment]
Thanks, @pearcej.

(We try to reserve GitHub for actually work on code, not so much for support questions.  This would have been better on `pretext-dev`.  [Appendix A: Welcome to the PreTeXt Community]( https://pretextbook.org/doc/guide/html/welcome.html#welcome)
