### ISSUE TITLE
Knowl styling consistency

### ISSUE THREAD

**Issue by ascholerChemeketa** [PreTeXtBook/pretext#2116]
Report from Jeremy Sylvestre email...

Small styling issue:

Go to
https://sites.ualberta.ca/~jsylvest/books/DLA1/section-inverses-theory.html

At the end of the first paragraph there's an xref to Proposition 4.5.1. Click to open the knowl. Then scroll down to the bottom of the knowl. This <proposition> has three proofs (for different substatements withing the proposition).

The styling for the three links to open the proof knowls is inconsistent. (But no such issue if you click "in-context" and go to the actual proposition.)

**Comment by rbeezer** [comment]
Closed via #2134
