### ISSUE TITLE
Normalize "document-id"

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#2153]
So it doesn't have new lines, etc.

Generally, identifiers (and similar) like this should not be **content** and should be **attributes**, where it is less likely that authoers will introduce stray whitespace.

**Comment by rbeezer** [comment]
`document-id` at e67a88c83a299a725d214a0b1870a562f1eabab8

And for good measure, `@edition` at cfcfc2338bd7ae6b0b4a5cc7658a20b62f2c0db3

Website rebuild later today.

Ping: @bnmnetp

**Comment by bnmnetp** [comment]
Thanks @rbeezer
