### ISSUE TITLE
url output for print

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#217]
The issue is that things like 

`<url href="http://mathbook.pugetsound.edu">MathBook XML</url>`

does not provide the web address to a reader of a print copy. If latex.print='yes', perhaps something should be done. 

See https://groups.google.com/forum/#!topic/mathbook-xml-support/2QOfrMNIFHc for a brief discussion and some ideas.

**Comment by rbeezer** [comment]
I think I like the idea of `clickable-text (real-url)` when `latex.print = 'yes'`

`\nolinkurl` might provide good line breaking.

BUT, hows this going to go over when used in a table?  Suddenly a cell of your carefully organized table gets a huge text dump?  Maybe this should only happen when inside a `<p>`?

**Comment by Alex-Jordan** [comment]
This is coming up with Active Calculus. At present, you can see many such links at http://faculty.gvsu.edu/boelkinm/Home/AC/preface-1.html. (Linking to the preface, but the issue appears throughout.)

In the print edition, link coloring is turned off for economy, so there is no way to know the address nor even an indication that there is a link at all.

If there is a table with a cell that pretty much only has a url, it makes me wonder what's going on here that this should be a table and not some kind of list. If the cell has more than just the url, it's already pretty long and maybe a paragraph cell is already in order. So maybe I'm not thinking hard enough, but I wouldn't be concerned about the issue raised.

`clickable-text (real-url)` sounds good to me. I guess all of it should actually clickable when reading the electronic PDF. But at the same time that doesn't matter since this is about print.

**Comment by rbeezer** [comment]
With a year's more experience, I'm now negative about automatically dumping a (possibly) very long and ugly URL into LaTeX output with no recourse.

An author should figure out if print output is important, and plan accordingly.  Blog-style links are not going to do very well in print no matter what.

I often make a live link with the real URL, then inside "c" make a human-readable version, typically without "htps://" etc.  If it is a short link (domain name only, or top-level directory) that works well.  If it is a very long ugly link, then the author should think about it.

AC preface links to AIM textbook initiative.  I don't think anything is lost or harmed by having a static version of the URL of the landing page for that project in all forms of output, along with the live one, which is undetectable in the print PDF.  I have done this numerous times in the Author's Guide.

AC "goals" has a link with text "growing body of scholarship."  I'm not even looking at that URL, and I think it should also be a reference where the authority is made clear, and the full URL is visible.  For *all* outputs.  OK, looked at URL by hovering.  I have no idea who is saying there is evidence.  I'd rather click on [1], get a knowl that says it is David Bressoud (now I know where this is coming from!), and then decide if I want to read more.

So, my point is - if you care about print, you are going to have to handle each case differently, with that awareness, much like the use of an eventual "static" element for 2-D interactive stuff.

If you think this needs more discussion, let's do it on  pretext-dev  and post a summary of what's here, including saying there is more detail here.

Thanks,
Rob
