### ISSUE TITLE
No separation between case/paragraphs and a following paragraph in LaTeX output

### ISSUE THREAD

**Issue by jjrsylvestre** [PreTeXtBook/pretext#2174]
In LaTeX output:

For source structure
````
proof
  p
  case
  case
  p
````
The final `p` is not a new paragraph but instead just continues on the last line of the preceding case.

Similarly, for source structure
````
paragraphs
  p
  p
p
````
there is a significant amount of vertical space preceding the `paragraphs` but no vertical space between the final `p` of the `paragraphs` and the new `p` outside of the `paragraphs`, making that final `p` look like it is part of the `paragraphs`.

**Comment by rbeezer** [comment]
Closed via #2175.
