### ISSUE TITLE
Notation in exercisegroups missing in latex

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#2184]
Similarly to #1419 notation elements are not being processed in exercise groups (or indeed, apparently, in exercises in them) in LaTeX.  A good fix seems to be to just ape exactly what was done there.

----

Caveat: I'm working on a slightly older PTX version because I need to finish a task which requires a version of PTX which doesn't need the pretext script to generate html.   But I did compare the `pretext-latex.xsl` files and I don't see any differences relative to that, nor any tickets about this specifically.  So I presume this is still valid.

**Comment by kcrisman** [comment]
Actually, this is also not in the schema (nor with exercises).  But some books do reserve certain difficult concepts to exercises (for the really elite student), and hence some notation, so it seems reasonable to support this.

**Comment by rbeezer** [comment]
Yes, I looked at the code, and then the schema, a few days ago.  Haven't had time to reply, as the Groups take precedence over issues.

Only in the structure of a `definition` or within a `p`.  If your `exercisegroup` has notation, use an `introduction` and put it into a contained `p`.

(Probably best to have discussions and questions in the Groups, and only move here when there is something that needs to be changed.)

**Comment by kcrisman** [comment]
> Yes, I looked at the code, and then the schema, a few days ago. Haven't had time to reply, as the Groups take precedence over issues.

Yes, I wasn't at all expecting an immediate (or any near-term) response - I was going to work on it properly, because I needed this, and thought it would be helpful to contribute.

> Only in the structure of a `definition` or within a `p`. If your `exercisegroup` has notation, use an `introduction` and put it into a contained `p`.

That always feels hackish (I'm pretty sure I've had to do it before), but I can live with it as long as I document it for myself in my project.  Thanks for clarifying.  

Should I whip up an example for the sample article?

----

> (Probably best to have discussions and questions in the Groups, and only move here when there is something that needs to be changed.)

In principle, but I don't think there is a neat line on *any* openly-developed software as to what a clear bug is versus something that needs developer discussion.  I felt this was in the former category - evidently that isn't the consensus view, but that is why I didn't raise the issue on a group.  I don't think it's of wide interest, at least, pretty technical.
