### ISSUE TITLE
<worksheet> and <page> aren't in the schema

### ISSUE THREAD

**Issue by rhinopotamus** [PreTeXtBook/pretext#2230]
I word-searched these two terms in the schema browser to make sure I knew who they could contain, but they're not there. Indeed they do not appear in `pretext.xsd`.

**Comment by rbeezer** [comment]
That tells you they are a work-in-progress and the schema for these objects is not final.  Better to ask on `pretext-support` before going straight to making an issue.  (There is no bug here.)

**Comment by rhinopotamus** [comment]
Got it, thanks. Would a feature request for more complete documentation on `<worksheet>` and its friends be better suited to `pretext-support`?

**Comment by davidfarmer** [comment]
Not quite: `<worksheet>` is a work in progress, so it needs discussion.

If it were a settled matter, then it would be appropriate to request better documentation.
