### ISSUE TITLE
`EXAMPLE-LIKE` titles missing in latex

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext#2248]
At some commit between CLI version 2.5 and 2.6, the styling for example-like blocks in latex changed resulting in the title not showing up.

**Comment by dbrianwalton** [comment]
It is specifically introduced at commit a78e9b1 "LaTeX: restore parskip as well as parindent for parboxes". I think it might have something to do with inherited styles in the tcolorbox environments.

**Comment by Alex-Jordan** [comment]
Sorry, this is something I added. I think @dbrianwalton grabbed the wrong commit hash though. My mistake is at the bottom of 6800dd61948877e348cb5331c393f8f913e6828d.

**Comment by dbrianwalton** [comment]
You're right Alex. I think I marked the last commit before the issue
appeared. Sorry if that was confusing.
