### ISSUE TITLE
Footnote on url moves outside of paragraph after page is processed

### ISSUE THREAD

**Issue by jjrsylvestre** [PreTeXtBook/pretext#2273]
I haven't found this behaviour in the current online version of the [sample article](https://pretextbook.org/examples/sample-article/html/) (though maybe I haven't looked thoroughly enough), but I do see it in the [sample book](https://sites.ualberta.ca/~jsylvest/pretext-dev/sample-book/front-colophon.html) --- the footnote on "external link" near the bottom of the page is moved outside of the paragraph where it is supposed to live.

If you open the source of the page, you see structure:
````
p
  (text)
  a
  details
    summary
      sup
    div
      code
  (text continues)
````
That's all good, but if you view the page in a browser and open the developer tools pane and inspect the source of the page after processing, you see structure
````
p
  (text)
  a
details
  summary
    sup
  div
    code
(text continues but not contained in any HTML element!)
````
Both the `details` element and the text that continues the `p` have been moved outside of the `p`.

Javascript issue?

**Comment by jjrsylvestre** [comment]
Doesn't seem to happen on the "external link" in the frontmatter of the sample book any more, but still happens on `bibinfo/website/url` if the `url` element contains link text.

For example, if I edit `pretext/examples/sample-book/frontmatter.xml` (or `pretext/examples/sample-book/frontmatter-noparts.xml` from

````
<website>
    <url href="http://abstract.pugetsound.edu" visual="abstract.pugetsound.edu"/>
</website>
````

to

````
<website>
    <url href="http://abstract.pugetsound.edu" visual="abstract.pugetsound.edu">Some Text</url>
</website>
````

(which would appear to be allowed by the schema)

then a footnote marker is added to "Some Text" in the html output, but the marker appears by itself on a new line with some vertical space in between.

See [live page of the sample book](https://sites.ualberta.ca/~jsylvest/pretext-dev/sample-book/front-colophon.html) and/or the attached image, where I have highlighted the issue in a red box.
![moving-footnote](https://github.com/user-attachments/assets/eeec5ffb-7a73-47e9-a015-fa95b748882a)

**Comment by ascholerChemeketa** [comment]
@jjrsylvestre Thanks for the report.

Just PR'd a fix in https://github.com/PreTeXtBook/pretext/pull/2300

Anywhere you see a true `<p>` tag (not `<div class="para">` in the code PreTeXt generates could produce a similar issue if it has block-level content.
