### ISSUE TITLE
Upgrade example-like blocks

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#294]
Not sure how much upgrading will happen.  But this **will** be consolidation and addition of several "blocks" or "environments" that look like examples.

Recently `example` allows for a `statement` and `solution` structure ( #248 ) so that will be the guiding property of `example-like` - it must make sense to have a `solution`.

This is partial progress on #85

**Comment by kcrisman** [comment]
> it must make sense to have a solution.

(But not necessary, correct?)

**Comment by rbeezer** [comment]
Yes, "could" not "must".

**Comment by rbeezer** [comment]
Thanks, Jiri.  So if you want to give that thing a name, we can add it to
the list of "theorem-like" objects since that is how it will behave.

Something like "example-result"?  But better?

Rob

**Comment by jirilebl** [comment]
I wonder however if the default styling of such a thing should be same as
example-like, although that is a minor nitpick.

I thought about it for a while and cannot think of anything better than
"example-result" or "example-claim" or perhaps "example-with-proof" or
"proved-example".

Best,

Jiri

**Comment by rbeezer** [comment]
Dear Jiri,

Now I'm a bit confused.  THEOREM-LIKE and EXAMPLE-LIKE are going to be XML 
entities that list all the environments/blocks of each type just once in teh 
code.  So a new block is (almost) a single change.  So the idea is to not 
customise these in style/form, but each will have a slightly different name.

So an EXAMPLE-LIKE will always have an optional "Solution"

A THEOREM-LIKE will always have an optional proof.  And proofs can be 
"detached", have "cases", etc.

But they could be Example 4.5, or Lemma 6.7, or Blatzo 9.8.

So do you want "<example-with-proof>" to have a "proof" with all teh associated 
functions, and maybe it just says "Example" where it might normally say "Theorem"?

Sorry if I am being a bit slow.

Rob

**Comment by jirilebl** [comment]
I'm sure the confusion is all mine.  I guess I am confusing two things here.

1) The need for an "example with proof" category of "thing" which is sort of like a theorem but named "Example" in the output.

2) What by default happens in the output, and I might be totally confused here.  If the fact that it is chunked in with "theorem-like" has no relevance on how the default xslt output is going to treat it, then ignore me.  But if the "theorem-like" list of entities are all going to be styled similarly and "example-like" are going to be styled similarly based on being in one of the two lists ... then that's what I had in mind.  That is, for example by default in the HTML output examples are "knowlified" but theorems are not (but their proofs are).  But my confusion could be that this is not at all the place to make this distinction, if so, feel free to ignore this second point completely.

**Comment by rbeezer** [comment]
`problem` and `question` tags implemented at d3f64038

I'm going to leave his open until I get to Jiri's example-cum-proof.
