### ISSUE TITLE
Document various things that aren't documented.

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#33]
As requested in #31, here is a ticket with a list of things that need to be documented.  I'll keep changing this list as things are done.
- The hierarchy of containers, e.g. that appendices only are at the level of chapters for LaTeX (and probably shouldn't work for HTML, though it does)
- The strict hierarchy in such environments - no `<p>` or other stuff outside the few legal containers in them.
- When you must use `<p>`, for instance apparently inside remarks.
- Math mode, ala percent discussion at #43
- What the heck the `<acro>` tag is for (?)
- _Exactly_ how to make an index - namely, `makeindex filename` for `filename.tex`
- The difference between `<md>`, `<me>`, `<mdn>`, `<men>`.  (And using `number="no"`.)  Eventually I figured it out, but because the `d` doesn't convey "rows" to me, I wasn't sure at first exactly what was going on.
- More to come.

**Comment by rbeezer** [comment]
Better than OK - it'll work great.

**Comment by rbeezer** [comment]
There is now an extensive discussion in the sample article about all the special, reserved and escape characters.

**Comment by kcrisman** [comment]
Awesome.

**Comment by rbeezer** [comment]
Definitions:  Now a complete example in sample article.

Theorem-like: Subsection 4.3 has been expanded.  It seems unnecessary to give an example of each, as they only vary by the actual element name.  I think there is now enough examples and enough guidance for folks to get started.

**Comment by davidfarmer** [comment]
If any of these items remain, a new issue should be created.
