### ISSUE TITLE
copy and paste don't work

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#330]
If you try to copy and paste from pdf, it doesn't work because indents don't show up, and sometimes even worse (nothing pastes if sufficiently complex).  Don't know if this is browser-dependent but I don't think so.

And I do think this would be something we'd want to support?

PS it DOES work if there are no indentations.

**Comment by davidfarmer** [comment]
At the (one) TUG conference I went to, there was a talk on this.
It is complicated and not something we should try to solve.

**Comment by kcrisman** [comment]
>
> At the (one) TUG conference I went to, there was a talk on this.
> It is complicated and not something we should try to solve.
>

But can someone *else* solve it for us?  This will be annoying to students
who use the pdf for whatever reason. Idea: if we can't cut and paste,
perhaps every code block could itself (also) be a hyperlink to a Sage cell
server with that code ...

**Comment by davidfarmer** [comment]
How about we make a non-PDF easily available and educate our
students to use the PDF for the right reason and not for
"whatever reason."

**Comment by kcrisman** [comment]
E.g. because someone has pdf and a local copy of Sage but doesn't have access to the html version of the book because they're not online?  That's a pretty common use case for me personally; free wifi is definitely not universal.

**Comment by rbeezer** [comment]
On 07/01/2016 06:19 PM, davidfarmer wrote:
> At the (one) TUG conference I went to, there was a talk on this.
> It is complicated and not something we should try to solve.

Agreed.  I have been careful about quotes and hyphens, but personally don't want 
to go much farther down this road.

For the record, here is the talk David references: 
https://tug.org/tug2014/abstracts/moore.txt

**Comment by kcrisman** [comment]
For laypeople: https://tex.stackexchange.com/questions/472099/how-to-configure-tcblisting-with-minted-to-allow-copy-paste-from-listing-with-wh
