### ISSUE TITLE
More whitespace control for sidebyside

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#431]
Right now the `margins` attribute for a `sidebyside` expects two percentages.  Its usefullness could be extended easily:

* One percentage: duplicate it for left and right margins.
* Several percentages: check that for `n` panels there are `n+1` percentages and use for left and right margins, in addition to the `n-1` inter-panel spacings.
* Two percentages, two or more panels: preserve current behavior.

**Comment by Alex-Jordan** [comment]
>> Several percentages: check that for n panels there are n+1 percentages and use for left and right margins, in addition to the n-1 inter-panel spacings.

Been thinking about this along with other sbs issues. I'm not sure you should specify one "margin" for the space between two items. The left item has a right margin and the right item has a left margin. Or maybe it's fine. But I'm not sure what to do about captions. Is a caption constrained to the same width as the image? Or can the caption spill some into what we'd call a "margin"?

Consider a drawing of a hydrogen atom. Say you only want it's electron cloud to end up 2cm wide, say about 10%. But you don't want the caption to be constrained to that small; you want it more like 30%. Do you make the width 30%? Then the atom image will be stretched to that big. Do you make the width 10%? The we need to let the caption extend into margins. Do you build white space into the image, to the left and right of the atom? (my suggestion in the forum.)

**Comment by rbeezer** [comment]
Yes, a left and right margin for the inter-panel spacing would allow control of the captions being wider that their panel.  That's a good point and a good idea.

(Right now they are constrained, I believe, but that could be relaxed easily).
