### ISSUE TITLE
Allow nested toc menus on left (or something like that)

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#44]
In a web interface it makes more sense to have a shorter list on the left of just chapters (say, or to whatever depth you want since you provide some configuration) but then allow either mouseover or clicking to expand that particular thing.  Say that it looks like
1. Foo
2. Bar
3. Foobar
   3.1 Chocolate foobar
   3.2 Vanilla foobar
4. Eggs

and then you want to see the list of subsections in 3.2, you could click or mouseover it, just like in zillions of very well-designed web pages like Amazon, nested javascript menus or whatnot.

Clearly this would need to be an option only, and maybe it should be tagged "wish list" or something, but figured I'd put it out there.

**Comment by rbeezer** [comment]
Yes, I'd love to see this option once we have some more expert CSS/JavaScript help.

**Comment by rbeezer** [comment]
This looks a lot like #27.

**Comment by kcrisman** [comment]
You are correct on both of them.  I guess I *really* want this feature :-)

**Comment by rbeezer** [comment]
Closed #27 as the duplicate, but still worth reading when the time comes.

**Comment by davidfarmer** [comment]
Collapsible TOC is part of the current major upgrade.
