### ISSUE TITLE
Multicolumn and MathJax can be a bit haywire

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#50]
HTML multicolumn lists with semi-complicated MathJax seem to sometimes put just one item on a line (or otherwise skip over certain items).

Two known examples: Judson's AATA Exercises 1.17 and 4.4.

Likely beyond our control and one to report to MathJax.

**Comment by Alex-Jordan** [comment]
I just visited the cited examples:
http://abstract.pugetsound.edu/aata/exercises-sets.html#hxX
http://abstract.pugetsound.edu/aata/exercises-cyclic.html#GKF

and I don't see the issue. Has the issue corrected itself with time and MathJax evolution? (Maybe in the first item, there is a vertical alignment issue, but that is separate from the issue reported here.)

**Comment by sean-fitzpatrick** [comment]
Maybe a different issue, but we don't get good behaviour for two column lists with math in APEX. Things look ok on desktop, but using Chrome on an Android phone, columns overlap unless you turn the phone sideways to get landscape orientation. See Theorem 1.3.8 here for example:
[apex-calculus/sec_limit_analytically.html](http://www.cs.uleth.ca/~fitzpat/apex-calculus/sec_limit_analytically.html)

**Comment by davidfarmer** [comment]
When two-column lists contain text, the text compresses
and the two column display (with gaps between columns)
is maintained.

What, other than math, is incompressible content in a list?
(Answer: a single word.  This is an issue when the list has
many columns)

The only way to avoid overlap with incompressible content,
is for the two-column to switch to one-column. (or mult-col
to switch to fewer-col).

If this issue is to stay open, then I would like to hear an
argument why it is okay for authors to put wide material
into multi-columns.

**Comment by sean-fitzpatrick** [comment]
In the case of conversions from LaTeX, we end up with multicolumn layouts that were designed for a wider pagewidth. Usually there's already some accounting for this (dropping from 3 or 4 columns down to 2).
The remaining problem -- at least for me -- could be considered lack of due diligence in quality control: building HTML and inspecting on a desktop or laptop doesn't always reveal problems with phone display.

The character width is fairly consistent across different browsers and screen sizes.
But character width drops sharply on a phone.
If a phone is held sideways (landscape orientation) the character width is the same as on a PC.
But if you turn the phone to the usual portrait orientation that most will use to read a document, the character width drops sharply. (I'm seeing about 70 characters in landscape, versus just over 30 in portrait.)

So "wide" is relative.

**Comment by Alex-Jordan** [comment]
I'd be in favor of multicolumn things (lists, exercisegroups) becoming single column on a small screen. If the styling has transitioned to the phone layout, just ignoring .cols2, etc. (The other "multicolumn" thing is sidebyside, where I'm not so sure.)

**Comment by sean-fitzpatrick** [comment]
Me too. I have some things in a sidebyside that probably shouldn't be.
In the same section referenced above, there are three videos that are all in reference to the same theorem (properties of limits). I put them in a sidebyside at 33% width, which looks fine on PC and in landscape, but they overlap on a phone in portrait.

I think the phone browser must report the value for 100% as the width in landscape, and it doesn't adjust for portrait. So an object that is 33% of landscape width is around 50% of portrait width and things don't fit.

So when I have time I'll go back and apply the lesson learned: don't do sidebyside videos.

**Comment by Alex-Jordan** [comment]
I think this issue could be closed, but perhaps only @rbeezer can close it. (I can only close issues that I opened myself.)

**Comment by davidfarmer** [comment]
Fixed (and we have new MathJax).
