### ISSUE TITLE
note in biblio doesn't look right

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#505]
In html, if you have a biblio with a note in it, then e.g. ref C.2.6 has in the Note knowl the text "NoteC.2.6.1" with no space between the Note and the C.2.6.1.    pdf this is irrelevant.

(Also, were we really expecting multiple notes per biblio item?)

**Comment by kcrisman** [comment]
@rbeezer Since this is the big week for PTX development figured I'd start commenting on things ... in this case, I think the issue might be no longer valid.  At least, I can't find anything like this cropping up.  If you confirm (or see a place where this might have been fixed) feel free to close.

**Comment by davidfarmer** [comment]
replaced by #1789
