### ISSUE TITLE
Clarify status of math in titles

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#513]
In running titles (pdf), things like
```
<title>The Integers Modulo <m>n</m></title>
```
show up as 
> The Integers Modulo N

Maybe that just means I'm using it wrong, but it would be nice to clarify this by raising an actual error in MBX (as opposed to a warning in tex), or to fix it.

**Comment by rbeezer** [comment]
Does the  n  change from lowercase to uppercase?

**Comment by kcrisman** [comment]
Does the n change from lowercase to uppercase?
>
>
Indeed it does. It also does not appear to be in math mode, though that is
hard to tell.

**Comment by rbeezer** [comment]
Content in titles moving various places is tricky, especially the math bits. 
But do-able.  Headings in PDF will be a sabbatical project.

Thanks for the report.

**Comment by rbeezer** [comment]
Inline math is now clearly allowed in titles, so the migration to PDF (especially the sidebar table of contents) will need investigation.

**Comment by davidfarmer** [comment]
Done
