### ISSUE TITLE
Request for a log file

### ISSUE THREAD

**Issue by twjudson** [PreTeXtBook/pretext#514]
Whenever I build a large project (e.g., a book), I get tons of terminal output.  I can mostly ignore this until something goes wrong at which time I have to scroll back up the terminal output to find out how to fix the problem.  This is usually a mess. It would be nice to have an optional log file.  Currently, it's possible to create something by redirecting the terminal output, but an option to generate a log file would be preferable.

**Comment by davidfarmer** [comment]
I think this is subsumed by CLI improvements,
