### ISSUE TITLE
Warn about an apparent introduction that is not marked as such

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#517]
We should be able to see some "p" leading a subdivision, with subsequent subdivisions following, suggesting an "introduction".  (And we could also suggest "conclusion".)

Why warn if we know what the problem is?  The warning would not be perfect, and the chunking code might get really complicated if we tried to be perfect in catching this.

But it seems common enough to attempt to automatically forestall some of this.

**Comment by kcrisman** [comment]
> We should be able to see some "p" leading a subdivision, with subsequent
> subdivisions following, suggesting an "introduction". (And we could also
> suggest "conclusion".)
>
>
>
+1 to the symmetry of conclusion suggested.  And +\infty for good
MBX-specific error messages; sometimes xsltproc is nearly as cryptic as
LaTeX.

**Comment by davidfarmer** [comment]
Surely done by now.
