### ISSUE TITLE
Masthead with no Table of Contents

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#525]
Live example below seems to be using **two** versions of the right margin.  Title gets wrapped with skinny margin, navigation buttons seem right, but dark and light grey background is using a wider margin.

http://mathbook.pugetsound.edu/beta/masthead-2017-02-08/NM.html

Possibly I should be writing more of the "table-of-contents" HTML, with some aspect of its interior empty?  Here is a version of the same source with "toc.level" set to "1".  It has some irrelevant differences, but a diff will clearly show what is missing from the above version.

http://mathbook.pugetsound.edu/beta/masthead-2017-02-08/NM-contents.html

@davidfarmer  - when you have time to investigate, let me know what I need to do different when an author (or the lack of subdivisions) requires a no-ToC look.  I suspect this is related to the nav buttons being pushed left, and I know that was a fiddle already.

Thanks,
Rob

**Comment by davidfarmer** [comment]
So much has happened with TOC and masthead that sure this is no longer relevant.
