### ISSUE TITLE
LaTeX source cleanup in mbx script

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#53]
Process LaTeX output (optionally) with Chris Hughes' package:

https://www.ctan.org/pkg/latexindent

to make the source even prettier (like for an archival copy of some publication).  Will likely require adding the right code to the mbx script, but I have not looked carefully.

**Comment by rbeezer** [comment]
It would be interesting to see the results of this program in action, and might be a useful addition to the `mbx` script.

**Comment by Alex-Jordan** [comment]
Set out to try applying this to the sample article .tex file. First thing to note is that my Macbook did not have the required perl modules. Using this as part of "standard" PTX will require some documentation about perl module installation.

**Comment by Alex-Jordan** [comment]
Some notes. At least right now in 2020, the perl that comes with Mac OS has issues that prevent at least one of the needed perl modules from being installed. Solution: install perl separately with homebrew or something. Then try running latexindent and it will tell you a perl module that is missing. `cpan Module::Name` to install it. Repeat.

After running `latexindent`, the sample article PDF comes out with significant differences, about 240 of them. (Adobe Acrobat has a handy "Compare PDFs" tool to jump you to the differences. ) A lot of that will go away after identifying all of the PTX "verbatim" environments and adding them to the config. And it's pointing me to some "differences" where I cannot make out an actual difference with my eyes.

Takeaway: we would need to maintain a `.yaml` file for using this on a PTX-produced .tex file. If for no other reason than to identify PTX-specific verbatim environments (`sageinput`, etc).

**Comment by kcrisman** [comment]
>
> Some notes. At least right now in 2020, the perl that comes with Mac OS
> has issues that prevent at least one of the needed perl modules from being
> installed. Solution: install perl separately with homebrew or something.
> Then try running latexindent and it will tell you a perl module that is
> missing. cpan Module::Name to install it. Repeat.
>

Yikes, that is not great.  Anything that requires Mac OS folks to do more
than necessary is a definite impediment to people using PTX for anything
needing the script.  (I know how much trouble installing jing-trang was and
that almost got me off of validating.)

**Comment by davidfarmer** [comment]
Long ago we have given up on making LaTeX output designed for human consumption.

If that has changed, open a new issue.
