### ISSUE TITLE
Make math bold inside term element

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#553]
We could recognize `m` with a parent (or ancestor?) `term` and wrap with `\mathbf{}`.  Euclidean n-space would be a good example.

**Comment by Alex-Jordan** [comment]
Every time I've used bold math, people object. It's not the bold they object to, just the change to upright instead of math-slanted. n-space might not be as objectionable as other things though.

**Comment by rbeezer** [comment]
Thanks, Alex.  I hadn't really investigated.  This package implements  \bm 
which would appear to preserve the italics or slant.

http://www.ctan.org/pkg/bm

But of course, this will not be available in MathJax most likely.

Rob

**Comment by davidfarmer** [comment]
There are many places where authors put math inside the term, when they shouldn't.

For example:  
"If <m>V</m> is a vector space then <m>W</m> is a <term>subspace of</term> <m>V</m> if...".
That is better than including the V in the term.  (Maybe the "of" should not
be in the term?  That is another topic for discussion.  I suggest that stealth
knowls provide a good context for making such decisions.)

A completely separate question is whether math amidst boldness should also
be bold.  It does not follow from first principles that it should.  (And as Alex already
pointed out, it is bad if the math bolding is done imperfectly.)

**Comment by rbeezer** [comment]
Math in titles (which get bolded, mostly) has come up before.  I know we load an 
"autobold.js" extension for MathJax.

Clearly a discussion for the list (not now!).  I just dropped a marker here, 
since I thought "Euclidean n-space" as a bolded term looked weird to my eye.  No 
plans to actually do anything right now.

Thanks for the comments.

Rob

**Comment by davidfarmer** [comment]
We implemented bold in math, so should be okay now.
