### ISSUE TITLE
video knowl switch

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#563]
We (ORCCA project) have a feature request for allowing videos to be inside a born-closed knowl.

Our initial motivation has to do with our particular usage of videos. We don't want them in your face; only opened and viewed for those readers who want them.

But I suspect this could be a more general use switch, helpful when a page has many videos that you don't want to all load at the same time.

**Comment by rbeezer** [comment]
Yes, I like it. +1.

I'm assuming a video will behave in a knowl - I've never tried.

**Comment by davidfarmer** [comment]
Made an issue for knowls:

https://github.com/BooksHTML/knowls/issues/12

**Comment by rbeezer** [comment]
Have a look at current Section 15 (Video) of sample article.  Several options related to how videos are presented and played.

For "not in your face" you can scale them very small, and open really big in a new page.  And you can pack several into a `sidebyside`.

Not objecting to knowls at all - but wondering if the above helps.  Yes, they would all still fire up their players, etc.  But you can hide that behind the big red button.

I bet a small video in the margin, which can open big elsewhere (reader's choice) might be popular.  Headed over to #653.

**Comment by davidfarmer** [comment]
Should work now.  Need to check after pending knowls refactor.
