### ISSUE TITLE
Allow print solutions of WeBWorK exercises

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#572]
It would be cool to be able to print out e.g. exams from WeBWorK problems but then also separately run it through some other switch and create _solutions_ for said exercises, sort of ala SageTeX.

@Alex-Jordan @oscarlevin

**Comment by Alex-Jordan** [comment]
Can you say more about this? (If you can remember after 2.5 years!) If I had a collection of WW problems that I wanted to use as an exam, I'd use WW itself. Put them in a problem set and print the problem set. You can print a WW hardcopy of a set with the answers showing or not showing. Not sure about full solutions, but if that is not an option it would be a feature to add to WeBWorK.

**Comment by Alex-Jordan** [comment]
@kcrisman I'm reviewing WeBWorK related issues, and I wondered if you wanted to say more about what you meant here. Or if we could close this issue.

**Comment by Alex-Jordan** [comment]
Hi @kcrisman, can this be closed?
