### ISSUE TITLE
allow output in sage to only be doctested

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#575]
One might want the output from a Sage element to show up in neither html nor pdf, but still show up for doctesting (perhaps like "sagesilent" in SageTeX).

**Comment by kcrisman** [comment]
(This probably is related to #87.)

**Comment by davidfarmer** [comment]
Doctesting is being revisited, so re-create this issue if it is relevant in the future.

**Comment by kcrisman** [comment]
I'm not really sure why this issue was closed.  Would it perhaps make more sense to cross-ref an issue/PR where the doctesting is being discussed?  I don't see that the relevance has diminished (or increased) since it was opened.

Possible use case, in addition to the convenience factor above: "reproducible research", where actually doing the full stats run would be incredibly long in output, but still should be checked in case there was a flawed algorithm previously in a given software package.
