### ISSUE TITLE
Allow computational cell input to be hidden

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#576]
This may be in already but I don't think so - there are various levels of hiding and automatic that Sage cell allows, so MBX should also support these - for example, when you don't want students to see code because that might include the answer.

**Comment by twjudson** [comment]
Agreed.  We need something like

 <sage>
                <input hide="yes">
                    x,y,t = var('x,y,t')
                    @interact
                    def _(f = in...

We need to hide input and possibly execute the cell automatically.  This is needed for interacts.

**Comment by davidaustinm** [comment]
This would be very useful for a variety of reasons.
