### ISSUE TITLE
Short naming of examples and inline exercises

### ISSUE THREAD

**Issue by byoshiwara** [PreTeXtBook/pretext#579]
Currently an example has a name like "Example 3.4.5" and that name is used to refer to (xref) it. We would like an option for the name to be simply "Example 5" and for it to be referenced as "Example 5 in Section 3.4"; but if the reference occurs in Section 3.4, then the reference would be simply "Example 5"

**Comment by rbeezer** [comment]
#61 is similar.

**Comment by davidfarmer** [comment]
Now there are many xref options, so reopen if still relevant.
