### ISSUE TITLE
Help with Kathy's formatting issues

### ISSUE THREAD

**Issue by kyoshiwara** [PreTeXtBook/pretext#590]
Here are my current difficulties: 

All of these are at  https://cdn.rawgit.com/byoshiwara/mfg/master/LinMod.html

1.  After a box, graph, or table, can there be a line space before the next line of text?
Example:  1.1.4 after "Intercepts of a Graph" box.

2.  If a Problem has more than one part, can part (a) start on the same line as the problem number?
Example:   1.1.7 Problem 31

3.  Can Homework Problems that are a table or graph appear on the same line as the problem number, instead of on the next line.
Example:  1.1.7 Problem #9, Problem 33

4.  After the instructions for a block of problems, can the problems NOT be indented?
Example: 1.1.7 Problems 13-18

5.  Sometimes lists of parts get out of order.
Example:   1.17 Problem 29

**Comment by davidfarmer** [comment]
1.  I have fixed.

2, 3, and 4 involve an empty p, which should be addressed first.

5. is part of a more general problem, which is in issue #588

**Comment by rbeezer** [comment]
Part 2:  Problem 30 has an empty "p", but Problem 31 does not.

Assuming Problem 30 is the issue, I need to know what to do with the `id` attribute on the paragraph.  Could it go on an empty span?

`<p id="p-2466"></p>`

**Comment by davidfarmer** [comment]
All seem to be fixed.  If not, submit a new issue.
