### ISSUE TITLE
Explain thin customization layers

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#604]
Add a topic to the Author's Guide that explains how to create XSLT for just two common purposes:
*  Set values of parameters
*  Kill off classes of elements, or particular elements (eg, by `title` or `xml:id`)

**Comment by kcrisman** [comment]
👍

**Comment by rbeezer** [comment]
See too, the discussion about instructor's resources at

https://groups.google.com/d/topic/pretext-dev/Y7Qvd2RumYs/discussion
