### ISSUE TITLE
Simplify single-content side-by-side

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#618]
When a `sidebyside` only has a single child, it is overkill to do the whole setup as if there were multiple panels (and output too much, too complicated).  See if this situation can be handled better, with the intent being cleaner output.

**Comment by rbeezer** [comment]
This will restore page-breaks for the `program` element used by itself in a `sidebyside`, whch is a regression at  44cd3b09

**Comment by davidfarmer** [comment]
For a couple years, sidebyside with a single child has not been viewed as proper markup.
