### ISSUE TITLE
Add support for worksheets

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#637]
Perhaps to make a book that is a collection of worksheets, or as adjuncts to more traditional material.

Perhaps markup for a division, similar to how `exercises` and `references` behave.

**Comment by rbeezer** [comment]
And Oscar Levin reminds us that we will need to specify large areas of whitespace for a reader to work.

**Comment by rbeezer** [comment]
Slides (eg Beamer, S5) would be another useful ancillary that might be implemented similarly.

**Comment by davidfarmer** [comment]
Much recent work on worksheets.
