### ISSUE TITLE
Other formats inside math elements

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#638]
Lon Mitchell asks about ASCIIMath and MathML inside a PreTeXt document.  Perhaps easy to convert to HTML, given MathJax's awareness of these. @davidfarmer  suggests pre-parsing to LaTeX to get PDF/print to cooperate.

Lon is willing to wait for interest from others, hence on the "wish list."  Record expressions of interest here.

**Comment by davidfarmer** [comment]
Long-term sustainable math markup will not involve authors thinking in terms of
AsciiMath or MathML, so closing.
