### ISSUE TITLE
Revise instructions for installing ImageMagick on Windows

### ISSUE THREAD

**Issue by sklarjk** [PreTeXtBook/pretext#648]
The latest build of ImageMagick (7.0.6) longer has the `convert.exe` built in.  So instructions should be added to the _MBX XML Authors' Guide_ that when installing, one should be sure to check the box that says "“Install Legacy Utilities."

**Comment by rbeezer** [comment]
Thanks, now you are really giving back.  ;-)

**Comment by davidfarmer** [comment]
CLI should make this obsolete.
