### ISSUE TITLE
idx inside fn

### ISSUE THREAD

**Issue by mitchkeller** [PreTeXtBook/pretext#672]
Right now the schema bans an index entry inside a footnote. Both HTML and LaTeX work, although when the fn that contains the idx is inside an activity, the knowl in the HTML output contains the entire activity (and with the fn knowled, a reader may wonder what's up). This might be showing me *why* idx inside fn is currently not allowed by the schema. I would not object to this being closed as wontfix. Mainly making an issue report here so there's some documentation of a decision on the matter.

(In reflecting on a lot of Bogart's footnotes, they probably should be asides or historicals.)

**Comment by rbeezer** [comment]
Well, you know my initial reaction - "Don't do that!"

But perhaps it can be accomodated.  Present algorithm, which needs attention for 
other reasons, goes

index knowl is first ancestor whose parent is a division

Thus all the way up to the whole activity.  But, as usual, a footnote is 
exceptional in almost every way.

**Comment by mitchkeller** [comment]
I really am OK with being told not to do that! (This time.) I wound up converting a very long footnote containing two me's to an aside earlier today and really liked the way it worked, so I will probably do that with this schema-violating footnote, too.

I found an xref buried inside an idx and decided that the HTML version will mitigate the reason he had done that in LaTeX and just removed the silliness without raising it.

**Comment by davidfarmer** [comment]
Going with the suggestion: Don't do that!"
