### ISSUE TITLE
Remove MathJax autobold extension

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#679]
Since it is causing problems.  And/or file a report to MathJax from #676.

But first investigate use, maybe in titles.  There was some discussion a while ago about the advisability of this anyway.

**Comment by Alex-Jordan** [comment]
I will leave my example posted in case this leads to filing a report to MathJax.

**Comment by Alex-Jordan** [comment]
Here is an example that should be at a stable url:
http://spot.pcc.edu/math/orcca/section-equations-and-inequalities-as-true-false-statements.html

The equations at the top of 2.2.1 are appearing as bold in Firefox, on my Mac, but should not. Have not tested other browsers/OSs. In source, they look like this:

```
        <p>An <term>equation</term><idx><h>equation</h></idx> is two mathematical expressions with an equals sign between them. The two expressions can be relatively simple or more complicated:</p>

        <sidebyside widths="47% 47%" margins="0%">
            <p>A relatively simple equation:<me>x+1=2</me></p>
            <p>A more complicated equation:<me>\left(x^2+y^2-1\right)^3=x^2y^3</me></p>
        </sidebyside>

        <p>An <term>inequality</term><idx><h>inequality</h></idx> is quite similar, but the sign between the expressions is one of these: <m>\lt</m>, <m>\leq</m>, <m>\gt</m>, <m>\geq</m>, or <m>\neq</m>.</p>

        <sidebyside widths="47% 47%" margins="0%">
            <p>A relatively simple inequality:<me>x\geq15</me></p>
            <p>A more complicated inequality:<me>x^2+y^2\lt1</me></p>
        </sidebyside>
```

**Comment by davidfarmer** [comment]
Seems to be resolved.
