### ISSUE TITLE
HTML heading levels strictly ordered

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#729]
`h1` for a page's overall title in masthead. then first division is `h2`, next division is `h3` etc.

`paragraphs` is always `h5` and headings of blocks will be `h6` as of work now on a branch.

So this needs to react to chunking code to compute a new "root level" for each page and compute section headers accordingly.

This is purely for accessibility, no CSS depends on these elements alone.

**Comment by davidfarmer** [comment]
Recent work of Alex J has addressed this.
