### ISSUE TITLE
Markup does not render in browser tab

### ISSUE THREAD

**Issue by ghost** [PreTeXtBook/pretext#775]
Browser tabs show the section title, but markup of text in the title (e.g., monospace font) does not render in the tab. Discussed at [https://groups.google.com/forum/#!msg/pretext-dev/VlY-lyvgrc0/x7OJ0XCJCwAJ](url)

**Comment by rbeezer** [comment]
On same thread, a new feature might be an attribute for `title` that carries a no-markup version, which would be enforced by being an attribute value.
