### ISSUE TITLE
CSS for pseudo-captions of videos

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#830]
Part of #732.  See masked YouTube videos near the bottom of the page.

http://mathbook.pugetsound.edu/examples/sample-article/html/section-video.html

`Click above to play`, `Click to pop-out`, and then on pop-out, `Reload page to ...` beneath.  Each is a centered `div` using an inline style.  They each function somewhat like a `figcaption` which might be a better choice for accessibility (they relate to directly preceding 2-D object).  How should the HTML/CSS go on these?

`figcaption.centered` or something more semantic?  Or should the pseudo-captions be bound more tightly to the video via some enclosing block (`figure.video-pop-out`, `figure.video-preview` `figure.video-masked`)?

The `Click to pop-out` should maybe even be a button.  And perhaps `Click above to play` is superfluous.

With suggestions/advice, I'll just make it happen and make it live.

**Comment by davidfarmer** [comment]
The "Click Above to Play" definitely is wrong.  It should be
obvious to the user that you click the thing to play, and it
does not convey the critical information that clicking will
Pop-out.

If there are only two cases, click to play in the page (possibly
choosing to make it full screen) and click to pop-out,
the it seems the only caption-like thing needed is "Click to pop-out".

Do we really need to support the case that you can choose
to view in page or pop-out?  Does not the full screen option
do enough?

**Comment by davidfarmer** [comment]
Seems to be irrelevant now.
