### ISSUE TITLE
Add question tag (and/or others)

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#85]
See https://groups.google.com/forum/#!topic/mathbook-xml-support/2D6Gne1XS-E for some discussion of having tags for open-ended problems or just general leitmotif questions - such as "question", "conjecture", "problem", and so forth.

**Comment by davidfarmer** [comment]
The following environments are in reasonably common usage and I think MBX should support them:

theorem-like environments
{
"theorem":"Theorem",
"computationaltheorem":"Computational Theorem",
"proposition":"Proposition",
"lemma":"Lemma",
"corollary":"Corollary",
"heuristic":"Heuristic",
"algorithm":"Algorithm"
}

example-like environments
{
"example":"Example",
"problem":"Problem",
"activity":"Activity",
"hypothesis":"Hypothesis",
"scratchwork":"Scratchwork",
"question":"Question",
"application":"Application",
"convention":"Convention"
}

definition-like environments
{
"definition":"Definition",
"conjecture":"Conjecture",
"note":"Note",
"claim":"Claim",
"fact":"Fact",
"identity":"Identity",
"assumption":"Assumption",
"situation":"Situation",
"hypothesis":"Hypothesis",
"setup":"Setup",
"observation":"Observation",
"notation":"Notation",
"construction":"Construction",
"keyidea":"Key Idea",
"conundrum":"Conundrum"
}

remark-like environments:
{"remark":"Remark",
"remarks":"Remarks",          
"scholium":"Scholium",        
"warning":"Warning",          
"case":"Case",                
"summary":"Summary",          
"solution":"Solution"}

**Comment by davidfarmer** [comment]
In SL2X I define 5 types of environments:
theorem-like
definition-like
remark-like
example-like
exercise-like

I have code for all 5 cases, and adding a new tag just involves
adding one line to the appropriate case.  It would be great if
it was similarly easy to do in MBX.

**Comment by davidfarmer** [comment]
There also are "paragraphs-like" environments, such as  "discussion" or "comments".
Should they be their own environment, or be a paragraphs with a title?

**Comment by oscarlevin** [comment]
I second this request for additional environments, or perhaps allow for different flavors of some main environments.  I'm thinking of something like theorems which sometimes I want to highlight because they are a "main theorem" compared to others which are still theorems, but are less important.  The latter should still be called a theorem, but should get a different weight to help students distinguish.  Perhaps the main theorems should have their proofs un-knowled, but the supplemental theorems have  the proof in a hidden knowl.  Should there be a main-theorem environment?  I don't know.

**Comment by Alex-Jordan** [comment]
In the same vein as Task and Activity: Investigation, Lab.

Also, are such things more "exercise-like" than "example-like"?

Also, can an Activity have sub Tasks? (And other similar parent-child relationships from these ~30 things?)

**Comment by kcrisman** [comment]
What's the status on this?  I think @rbeezer  is planning to add many soon...

**Comment by rbeezer** [comment]
Original request implemented at d3f64038

I'm going to leave this open as we work through David's list.

**Comment by kcrisman** [comment]
Yippee!

**Comment by rbeezer** [comment]
(This is posted verbatim on mathbook-xml-support but has a good update and some things to do.)

I have refactored, consolidated, cleaned-up, and added 27 of the blocks, as listed below with their "-LIKE" categories.  "Blocks" are numbered, have titles, are targets of cross-references, are reasonably and optionally knowlizable, styled to be slightly set apart from the running narrative.


definition: unique now, an equivalence between a term and mathematical statement, presentation is normal text.

theorem: any mathematical statement which might carry a proof, presentation is italic for statement.

axiom: just like theorem, but cannot have a proof.

remark: simple, just "plain" text.

example: like a remark, but may have a solution (and expect to add hint, answer).

project: like an example, but has independent numbering scheme


This began when KDC asked for "question."  Then David's analysis of 567,315 published papers suggested a few more.  It will end when I get detached proofs done, perhaps make "statement" optional, add more introuction and conclusion, remove all duplicate LaTeX labels and HTML id, consolidate DTD, and a host of other related requests or bugs. 

Following has similar structures I'll be working on next, three common blocks that we already accomodate in other ways, and one near duplicate.  Here are my comments, suggestions and questions for you.  Your informed advice as author-mathematicians is greatly appreciated.  I can only guess about some of these.

application:  I like this one, but can't be sure which bucket it belongs in?  An example maybe, but what is the solution?

scholium:  my dictionary says, "a marginal note written by a scholiast (a commentator on ancient or classical literature))", so I'd like to save this for when we do marginal notes generally

conundrum: dictionary says "a difficult problem", so EXAMPLE-LIKE?

construction: is this a second sort of definition?

keyidea: REMARK-LIKE?  is "insight" a better name, or different?

scratchwork: not sure what this is, and don't really even like it.  REMARK-LIKE?

summary: is this structural or randomly placed?  Shouldn't it come at the *end* of something? A titled conclusion?

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DEFINITION-LIKE definition
THEOREM-LIKE theorem|corollary|lemma|algorithm|proposition|claim|fact|identity
AXIOM-LIKE   axiom|conjecture|principle|heuristic|hypothesis|assumption
REMARK-LIKE  remark|convention|note|observation|warning
EXAMPLE-LIKE example|question|problem
PROJECT-LIKE project|activity|exploration|task

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Needs Work:

list: the numbered block surrounding an ol, ul, dl
figure-like: figure, table, listing, sidebyside
exercises: inline and sectional

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Remainders from David Farmer's list at
https://github.com/rbeezer/mathbook/issues/85

Extant:
"notation":"Notation",
"solution":"Solution"
"case":"Case",

Near Duplicate:
"remarks":"Remarks", (have singular)

Unimplemented:

example-like environments
{
"scratchwork":"Scratchwork",
"application":"Application",
}

definition-like environments
{
"situation":"Situation",
"setup":"Setup",
"construction":"Construction",
"keyidea":"Key Idea",
"conundrum":"Conundrum"
}

remark-like environments:
{
"scholium":"Scholium",
"summary":"Summary",
}

**Comment by rbeezer** [comment]
Jessica Slar asked about a `notation` environment.

**Comment by davidfarmer** [comment]
Many new *-like environments have been implemented in the past 6 years.

If yet more are still needed, make a new issue.
