### ISSUE TITLE
Sage Cell fallback

### ISSUE THREAD

**Issue by rbeezer** [PreTeXtBook/pretext#86]
Suppose you are viewing the HTML output "locally," or without a connection to the Sage Cell Server.  Since we may put expected output into the source so that we can doctest and print it as part of a PDF, maybe the HTML could fall back s needed to a static rendering and display the expected output.

**Comment by kcrisman** [comment]
YES please have this.  (Though that would require me personally to have output lines.  What should happen for interacts/plots?)

**Comment by davidfarmer** [comment]
This is implemented in the current "no JavaScript" improvements.
