### ISSUE TITLE
One way to do Sage things

### ISSUE THREAD

**Issue by kcrisman** [PreTeXtBook/pretext#87]
As requested, though I figure at least one more vote is needed.

> ```
> <sage type="plot" xml:id="really-really-cool-graphic"> 
>      <input>plot(really_cool_graphic)</input> 
> </sage> 
> ```
> 
> This seems useful.  One thing I find a little annoying about SageTeX is the need 
> to remember a lot of different tags for different ways to use Sage.  But two 
> votes probably isn't enough to change that... ?

**Comment by kcrisman** [comment]
It's not clear why this issue was closed.

**Comment by davidfarmer** [comment]
As I said in the linked issue, doc testing is a topic of discussion, so this (or anything
related to doctesting) can be added to that if it becomes relevant.

Outside the context of work on doctesting (whenever that actually happens) this issue
is not helpful.

**Comment by kcrisman** [comment]
This was a not a suggestion about doctesting - the example can't even be doctested, other than as to whether the plot command fails.  This issue is about the possibility of having only one Sage-type element, instead of both `<sage>` and `<sageplot>` (and perhaps other variants down the line such as `<interactive>` Sage elements, though I'm not sure what the status of that is).  That is to say, preventing unwanted proliferation of elements - but if these are not seen as too proliferated by anyone else, that is fine and the issue can be closed.

I had mentioned this one in #575 because presumably this suggestion could be connected to doctesting, but that is certainly not necessary for considering this issue.
