### ISSUE TITLE
Working with an incomplete LaTeX installation

### ISSUE THREAD

**Issue by geometryof** [PreTeXtBook/pretext#910]
_(The following is a summary of a recent discussion with Rob Beezer, who requested this report and suggested that this issue should be addressed in the Publisher's Guide.)_

Some users may find their LaTeX installation inadequate to process the output generated by PreTeXt.  One solution is of course to (re)install a full copy of LaTeX, with all optional packages, but that may not be possible or desirable.  An alternative is to go directly to CTAN (a Google search for "CTAN" plus the package name should work) and download the necessary packages manually.  Details will depend on individual installations, but typically require copying the subdirectory containing the style files into .../texmf/tex/latex/PACKAGE, then possibly updating the TeX search path (e.g. with mktexlsr).

The challenge, however, is to figure out which packages are necessary.  I recently went through this process on 3 different Linux machines, each with a different OS and level of partial LaTeX installation.  Trial and error works, but is painful.  So below is my worst-case list of the packages I needed to install from CTAN, some of which were already present but needed to be upgraded:
    caption, enumitem, environ, etoolbox, extpfeil, hyperref, ifexetex, mathtools, oberdiek,
    pgf, pgfplots, tcolorbox, tkz-base, tkz-euclide, tkz-graph, trimspace.
This list may, of course, be incomplete; there's no easy way to document which packages I started with.  Conversely, not everything on this list may be necessary, depending for instance on what graphics formats you use.  However, it did seem to be essential to update hyperref to the version on CTAN; this was true even on the brand-new machine with a current OS.

(Some versions of hyperref appear to define \theHfigure without checking whether it's already defined.  I had some success by adding the line
    \let\theHfigure\relax
immediately before loading hyperref, but this problem disappeared once everything was updated, including hyperref.)

You mileage may vary.  Hopefully, this conversation will eventually lead to a list of suggested packages, although any such list should of course be viewed as a moving target.

**Comment by davidfarmer** [comment]
CLI should make this obsolete.
