### ISSUE TITLE
Add Inline image element

### ISSUE THREAD

**Issue by pseeburger** [PreTeXtBook/pretext#920]
I suggest making a way to allow inline images.  These may be used for a number of applications, but mine is for explaining how to use various toolbar buttons with image icon in my app.

Here is a link to the discussion on this topic in the PreTeXt development forum.

[https://groups.google.com/d/topic/pretext-support/fdV-uqLrzRQ/discussion](https://groups.google.com/d/topic/pretext-support/fdV-uqLrzRQ/discussion)

**Comment by davidfarmer** [comment]
General inline images are problematic. The cases in this thread can likely be handles in other ways.
