### ISSUE TITLE
Punctuation in biblio entry

### ISSUE THREAD

**Issue by davidfarmer** [PreTeXtBook/pretext#949]
In the sample article there are thing like:
< year >2021< / year >,

and

< number >4< /number >,

In both cases, the comma should not be in the source.  Depending on the chosen
bibliography style, appropriate punctuation will be added.

Since the HTML version looks okay, I gather that "biblio" is not yet fully implemented.

A model for the tags could be BibTeX.

**Comment by kcrisman** [comment]
In this case I agree that would be very helpful, but I don't think there is any structure along those lines or I would have used it in the past.  Count me as a supporter of structuring this.

**Comment by davidfarmer** [comment]
I should have mentioned the reason I noticed this: the prettyprinter puts the "year"
entry on a line by itself.  So now the comma is on a new line and there is a space
before the comma in the output.

**Comment by rbeezer** [comment]
Bibliographies are the one big hole in PreTeXt.  Nobody has complained.  ;-)  But to support a broader range of disciplines it **will** be necessary to do better.  Plan is to support the "Citation Stylesheet Language", but despite a lot of research there does not seem to be a quick way to do this.

Are you able to put some sort of workaround in place for now?

**Comment by davidfarmer** [comment]
Bibliographies are also a big hole in SL2X.  I would consider thinking
seriously about that in a month or two (other PTX development having
higher priority).  One motivation for me is to establish connections
between bibliographic entries in the math research literature.

For now, probably I will adjust the prettyprinter to move punctuation
directly after the end of line tag.  (An alternative is to do that
in the XSLT, but I'd rather keep temporary hacks out of the PTX code.)

**Comment by davidfarmer** [comment]
I implemented new biblio options, which are still far from what we want.
This issue is not helpful.
