### ISSUE TITLE
class for video

### ISSUE THREAD

**Issue by Alex-Jordan** [PreTeXtBook/pretext#962]
The iframe containing a video should get a class for styling (like a frame). At least with YouTube playlists, it is not currently getting a class.

**Comment by rbeezer** [comment]
This was raised again in the vicinity of

https://groups.google.com/d/msg/pretext-support/qTIKAwA5jjY/uqTzcDytCQAJ

**Comment by rbeezer** [comment]
I see a `class="video"` in the code for every `iframe` construction.  Re-open if you think I missed one, @Alex-Jordan?
